import type { WorkshopParcelPlan } from "./workshopTransport";
import { useFineBinderyWorkspace } from "@/marketplace/i18n/FineBinderyWorkspaceContext";
export const emptyWorkshopParcelPlan = (): WorkshopParcelPlan => ({
  fromAddress: { name: "", line1: "", line2: null, postalCode: "", city: "", countryCode: "FR", phone: null },
  toAddress: { name: "", line1: "", line2: null, postalCode: "", city: "", countryCode: "FR", phone: null },
  parcel: { weightGrams: 0, lengthMm: 0, widthMm: 0, heightMm: 0 },
});
const copy = {
  fr: { from: "Expéditeur", to: "Destinataire", name: "Nom", line1: "Adresse", postalCode: "Code postal", city: "Ville", countryCode: "Pays (code à 2 lettres)", weightGrams: "Poids du colis emballé (g)", lengthMm: "Longueur (mm)", widthMm: "Largeur (mm)", heightMm: "Hauteur (mm)", reverse: "Reprendre les adresses aller en sens inverse", options: "Consulter les services et prix du transporteur", missing: "Choisissez la commande et complétez les adresses et le colis.", unavailable: "Tarifs indisponibles pour ce trajet. Vous pouvez enregistrer un transport déjà organisé avec son coût et ses conditions de couverture vérifiés.", note: "Consultation uniquement : aucun achat d’étiquette. Le prix fournisseur, sa fiscalité et sa couverture sont à vérifier avant engagement.", label: "Étiquette PDF privée", upload: "Ajouter une étiquette PDF existante (5 Mo max.)" },
  en: { from: "Sender", to: "Recipient", name: "Name", line1: "Address", postalCode: "Postcode", city: "City", countryCode: "Country (2-letter code)", weightGrams: "Packed parcel weight (g)", lengthMm: "Length (mm)", widthMm: "Width (mm)", heightMm: "Height (mm)", reverse: "Use outbound addresses in reverse", options: "View carrier services and prices", missing: "Choose the order and complete the addresses and parcel details.", unavailable: "Rates are unavailable for this journey. You can record transport already arranged with its verified cost and coverage conditions.", note: "Read-only enquiry: no label purchase. Verify the provider price, tax and coverage before committing.", label: "Private PDF label", upload: "Add an existing PDF label (5 MB max.)" },
  de: { from: "Absender", to: "Empfänger", name: "Name", line1: "Adresse", postalCode: "Postleitzahl", city: "Ort", countryCode: "Land (2 Buchstaben)", weightGrams: "Gewicht des verpackten Pakets (g)", lengthMm: "Länge (mm)", widthMm: "Breite (mm)", heightMm: "Höhe (mm)", reverse: "Hinweg-Adressen für den Rückweg verwenden", options: "Dienste und Preise des Transporteurs anzeigen", missing: "Wählen Sie den Auftrag und ergänzen Sie Adressen und Paketdaten.", unavailable: "Für diese Strecke sind keine Tarife verfügbar. Bereits organisierter Transport kann mit überprüften Kosten und Deckungsbedingungen erfasst werden.", note: "Nur Abfrage: kein Etikettenkauf. Prüfen Sie Preis, Steuer und Deckung vor einer Verpflichtung.", label: "Privates PDF-Etikett", upload: "Vorhandenes PDF-Etikett hinzufügen (max. 5 MB)" },
  it: { from: "Mittente", to: "Destinatario", name: "Nome", line1: "Indirizzo", postalCode: "Codice postale", city: "Città", countryCode: "Paese (codice a 2 lettere)", weightGrams: "Peso del pacco imballato (g)", lengthMm: "Lunghezza (mm)", widthMm: "Larghezza (mm)", heightMm: "Altezza (mm)", reverse: "Usare gli indirizzi di andata invertiti", options: "Consultare servizi e prezzi del trasportatore", missing: "Scegliete l’ordine e completate indirizzi e pacco.", unavailable: "Tariffe non disponibili per questo tragitto. Potete registrare un trasporto già organizzato con costi e condizioni di copertura verificati.", note: "Solo consultazione: nessun acquisto di etichette. Verificate prezzo, imposte e copertura prima di impegnarvi.", label: "Etichetta PDF privata", upload: "Aggiungere un’etichetta PDF esistente (max. 5 MB)" },
  es: { from: "Remitente", to: "Destinatario", name: "Nombre", line1: "Dirección", postalCode: "Código postal", city: "Ciudad", countryCode: "País (código de 2 letras)", weightGrams: "Peso del paquete embalado (g)", lengthMm: "Longitud (mm)", widthMm: "Anchura (mm)", heightMm: "Altura (mm)", reverse: "Usar las direcciones de ida invertidas", options: "Consultar servicios y precios del transportista", missing: "Elija el pedido y complete las direcciones y el paquete.", unavailable: "No hay tarifas disponibles para este trayecto. Puede registrar un transporte ya organizado con coste y cobertura verificados.", note: "Solo consulta: no se compra ninguna etiqueta. Verifique precio, impuestos y cobertura antes de comprometerse.", label: "Etiqueta PDF privada", upload: "Añadir una etiqueta PDF existente (máx. 5 MB)" },
};
export function useWorkshopTransportCopy() {
  const { locale } = useFineBinderyWorkspace();
  return copy[locale];
}
