import { SectionHead, SHELL } from "@/marketplace/pages/landing/LandingChrome";
import { Photograph } from "@/marketplace/pages/landing/Photograph";
import { PHOTO_SIZES } from "@/marketplace/pages/landing/photos";
import { usePageViewTracking } from "@/build/pages/public/usePageViewTracking";
import { FineBinderyFooter, FineBinderyHeader, FineBinderyIntakeCta } from "./FineBinderyChrome";
import { FEATURED_WORKSHOP } from "./content";
import { fineBinderyCopy } from "@/marketplace/i18n/fineBinderyCopy";
import { ENGINE_LOCALE, fineBinderyDirectoryPath, type FineBinderyLocale } from "@/marketplace/i18n/fineBinderyLocale";
import { specialtyName } from "@/marketplace/i18n/fineBinderyGlossary";
import { useFineBinderyDocumentLocale } from "@/marketplace/i18n/FineBinderyLanguageSwitch";
import {
  FERRIERE_FINE_BINDERY_OFFER_KEYS,
  FERRIERE_SERVICE_PHOTO_CREDIT,
  FERRIERE_SERVICE_PHOTO_SOURCE,
  ferriereServicePhoto,
} from "@/marketplace/pages/pricing/ferriereServiceIllustrations";

export function FineBinderyLandingPage({ locale = "en" }: { locale?: FineBinderyLocale }) {
  const copy = fineBinderyCopy(locale); useFineBinderyDocumentLocale(locale); usePageViewTracking(ENGINE_LOCALE[locale]);
  return <div className="mr-site fb-site flex min-h-screen flex-col bg-mr-paper text-mr-graphite"><FineBinderyHeader locale={locale} /><main id="top">
    <section className={`${SHELL} pt-14 pb-16 sm:pt-20 sm:pb-20 lg:pt-24 lg:pb-28`}><div className="grid items-center gap-12 lg:grid-cols-12 lg:gap-14"><div className="lg:col-span-7"><p className="mr-eyebrow">{copy.home.eyebrow}</p><h1 className="mr-display mt-6 text-mr-ink">{copy.home.title}</h1><p className="mr-lead mt-7 max-w-[36rem]">{copy.home.lead}</p><div className="mt-9 flex flex-wrap items-center gap-x-8 gap-y-4"><FineBinderyIntakeCta locale={locale} /><a href="#offers" className="mr-link mr-tap text-[1.0625rem]">{copy.home.discover}</a></div><p className="mr-small mt-8 max-w-[36rem]">{copy.home.proof}</p></div><div className="lg:col-span-5">{FEATURED_WORKSHOP.image ? <Photograph photo={FEATURED_WORKSHOP.image} sizes={PHOTO_SIZES.hero} ratio="landscape" priority alt={FEATURED_WORKSHOP.imageAlt ?? FEATURED_WORKSHOP.name} /> : <Photograph shotBrief="A European bookbinder sewing a volume by hand at a daylight workbench" sizes={PHOTO_SIZES.hero} ratio="landscape" priority alt={FEATURED_WORKSHOP.imageAlt ?? FEATURED_WORKSHOP.name} />}<p className="mr-meta mt-3">{FEATURED_WORKSHOP.name} · {FEATURED_WORKSHOP.city}, {copy.common.france}</p></div></div></section>
    <section className="bg-mr-paper-warm"><div className={`${SHELL} py-section-sm sm:py-section`}><SectionHead eyebrow={copy.home.benefitsEyebrow} title={copy.home.benefitsTitle} lead={copy.home.benefitsLead} /><div className="mt-12 grid gap-x-12 gap-y-10 sm:grid-cols-2 lg:mt-16">{copy.home.benefits.map((item, index) => <div key={item.title} className="border-t border-mr-rule pt-5"><span className="mr-meta">{String(index + 1).padStart(2, "0")}</span><h2 className="mr-heading mt-3 text-mr-ink">{item.title}</h2><p className="mr-body mt-2">{item.body}</p></div>)}</div></div></section>
    <section id="offers" className={`${SHELL} scroll-mt-32 py-section-sm sm:py-section`}><SectionHead eyebrow={copy.home.offersEyebrow} title={copy.home.offersTitle} /><p className="mr-meta mt-5">{copy.home.photoCredit}:{" "}<a className="mr-link" href={FERRIERE_SERVICE_PHOTO_SOURCE}>{FERRIERE_SERVICE_PHOTO_CREDIT}</a></p><div className="mt-12 grid gap-10 sm:grid-cols-2">{copy.home.offers.map((item, index) => { const photo = ferriereServicePhoto(FERRIERE_FINE_BINDERY_OFFER_KEYS[index]); return <div key={item.title} className="border-t border-mr-rule-strong pt-5"><img src={photo.src} srcSet={photo.srcSet} sizes="(min-width: 1024px) 570px, (min-width: 640px) 50vw, 100vw" alt="" loading="lazy" decoding="async" className="mb-5 aspect-[4/3] w-full bg-mr-ink/5 object-cover" /><h2 className="mr-heading text-mr-ink">{item.title}</h2><p className="mr-body mt-2">{item.body}</p><div className="mt-5"><FineBinderyIntakeCta locale={locale} variant="outline" size="compact" /></div></div>; })}</div></section>
    <section id="how-it-works" className="scroll-mt-32 bg-mr-paper-warm"><div className={`${SHELL} py-section-sm sm:py-section`}><SectionHead eyebrow={copy.home.howEyebrow} title={copy.home.howTitle} /><ol className="mt-12 grid gap-10 sm:grid-cols-2 lg:grid-cols-3">{copy.home.steps.map((title, index) => <li key={title} className="border-t border-mr-rule-strong pt-5"><span className="mr-meta">{String(index + 1).padStart(2, "0")}</span><p className="mr-heading mt-3 text-mr-ink">{title}</p></li>)}</ol></div></section>
    <section id="workshops" className={`${SHELL} scroll-mt-32 py-section-sm sm:py-section`}><SectionHead eyebrow={copy.home.workshopsEyebrow} title={copy.home.workshopsTitle} lead={copy.home.workshopsLead} /><div className="mt-12 grid gap-10 lg:grid-cols-12"><div className="lg:col-span-6">{FEATURED_WORKSHOP.image ? <Photograph photo={FEATURED_WORKSHOP.image} sizes={PHOTO_SIZES.artisan} ratio="landscape" alt={FEATURED_WORKSHOP.imageAlt ?? FEATURED_WORKSHOP.name} /> : <Photograph shotBrief="Close view of fine hand binding tools, thread and leather on a European workshop table" sizes={PHOTO_SIZES.artisan} ratio="landscape" alt={FEATURED_WORKSHOP.imageAlt ?? FEATURED_WORKSHOP.name} />}</div><div className="lg:col-span-6"><h2 className="mr-title text-[1.75rem] text-mr-ink">{FEATURED_WORKSHOP.name}</h2><p className="mr-small mt-2">{FEATURED_WORKSHOP.artisan ? `${FEATURED_WORKSHOP.artisan} · ` : ""}{FEATURED_WORKSHOP.city}, {copy.common.france}{FEATURED_WORKSHOP.since ? ` — ${copy.home.established} ${FEATURED_WORKSHOP.since}` : ""}</p><h3 className="mr-eyebrow mt-8">{copy.common.skills}</h3><p className="mr-body mt-3">{FEATURED_WORKSHOP.specialties.map((value) => specialtyName(value.toLowerCase().replaceAll(" ", "_"), locale)).join(" · ")}</p><p className="mr-small mt-8 text-mr-muted">{copy.home.selected}</p><a href={fineBinderyDirectoryPath(locale)} className="mr-link mr-tap mt-8 inline-flex text-[1.0625rem]">{copy.home.discoverWorkshops}</a></div></div></section>
    <section className="bg-mr-ink text-mr-paper"><div className={`${SHELL} py-section sm:py-section-lg`}><SectionHead eyebrow={copy.home.trustEyebrow} title={copy.home.trustTitle} tone="paper" /><ul className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{copy.home.trust.map((title, index) => <li key={title} className="border-t border-mr-paper/25 pt-5"><span className="mr-meta">{String(index + 1).padStart(2, "0")}</span><p className="mr-heading mt-3 text-mr-paper">{title}</p></li>)}</ul></div></section>
    <section className={`${SHELL} py-section-sm sm:py-section`}><SectionHead eyebrow={copy.home.shippingEyebrow} title={copy.home.shippingTitle} lead={copy.home.shippingLead} /></section>
    <section id="faq" className="scroll-mt-32 bg-mr-paper-warm"><div className={`${SHELL} py-section-sm sm:py-section`}><SectionHead eyebrow={copy.home.faqEyebrow} title={copy.home.faqTitle} /><div className="mt-10 max-w-[42rem] divide-y divide-mr-rule-strong">{copy.home.faq.map((item) => <details key={item.question} className="group py-5"><summary className="mr-body flex cursor-pointer list-none items-center justify-between gap-4 font-semibold text-mr-ink">{item.question}<span aria-hidden="true">＋</span></summary><p className="mr-body mt-3">{item.answer}</p></details>)}</div></div></section>
    <section className={`${SHELL} py-section-sm text-center sm:py-section`}><h2 className="mr-title mx-auto max-w-[34rem] text-mr-ink">{copy.home.finalTitle}</h2><p className="mr-lead mx-auto mt-5 max-w-[36rem]">{copy.home.finalLead}</p><div className="mt-8"><FineBinderyIntakeCta locale={locale} /></div></section>
  </main><FineBinderyFooter locale={locale} /></div>;
}
