import { useMemo, useState } from "react";
import { PUBLIC_LANGUAGES, PUBLIC_MATERIALS, PUBLIC_TECHNIQUES } from "@/marketplace/binders/fineBinderyProfile";
import { FineBinderyFooter, FineBinderyHeader, FineBinderyIntakeCta } from "./FineBinderyChrome";
import { fineBinderyCopy } from "@/marketplace/i18n/fineBinderyCopy";
import { countryName, languageName, specialtyName, techniqueName } from "@/marketplace/i18n/fineBinderyGlossary";
import { fineBinderyDirectoryPath, fineBinderyProfilePath, type FineBinderyLocale } from "@/marketplace/i18n/fineBinderyLocale";
import { useFineBinderyDocumentLocale } from "@/marketplace/i18n/FineBinderyLanguageSwitch";

type DirectoryProfile = { slug: string; path: string; workshopName: string; professionalName: string; city: string; countryCode: string; bio: string; languages: string[]; skills: { slug: string; label: string; labelEn: string }[]; imageUrl: string | null };
type PublicProfile = Awaited<ReturnType<typeof import("@/marketplace/services/fineBinderyProfile.data.functions").getPublicFineBinderyProfile>>;
const SHELL = "mx-auto w-full max-w-[78rem] px-5 sm:px-8 lg:px-12";

export function FineBinderyDirectoryPage({ profiles, locale }: { profiles: DirectoryProfile[]; locale: FineBinderyLocale }) {
  const copy = fineBinderyCopy(locale); useFineBinderyDocumentLocale(locale);
  const [country, setCountry] = useState(""); const [specialty, setSpecialty] = useState(""); const [language, setLanguage] = useState("");
  const filtered = useMemo(() => profiles.filter((p) => (!country || p.countryCode === country) && (!specialty || p.skills.some((s) => s.slug === specialty)) && (!language || p.languages.includes(language))), [profiles, country, specialty, language]);
  const specialties = useMemo(() => [...new Set(profiles.flatMap((p) => p.skills.map((s) => s.slug)))].sort((a, b) => specialtyName(a, locale).localeCompare(specialtyName(b, locale), locale)), [profiles, locale]);
  const countries = useMemo(() => [...new Set(profiles.map((p) => p.countryCode))].sort(), [profiles]);
  return <div className="mr-site flex min-h-screen flex-col bg-[#f7f3eb] text-[#243128]"><FineBinderyHeader locale={locale} /><main className="flex-1">
    <section className={`${SHELL} py-14 sm:py-20`}><p className="mr-eyebrow text-[#8a6235]">{copy.directory.eyebrow}</p><h1 className="mr-title mt-5 max-w-4xl text-4xl leading-tight text-[#17231c] sm:text-6xl">{copy.directory.title}</h1><p className="mr-lead mt-6 max-w-2xl">{copy.directory.lead}</p></section>
    <section className="border-y border-[#d9d1c4] bg-[#efe9de]"><div className={`${SHELL} grid gap-4 py-5 sm:grid-cols-3`}>
      <Filter label={copy.directory.country} value={country} onChange={setCountry}><option value="">{copy.directory.allCountries}</option>{countries.map((code) => <option key={code} value={code}>{countryName(code, locale)}</option>)}</Filter>
      <Filter label={copy.directory.specialty} value={specialty} onChange={setSpecialty}><option value="">{copy.directory.allSpecialties}</option>{specialties.map((key) => <option key={key} value={key}>{specialtyName(key, locale)}</option>)}</Filter>
      <Filter label={copy.directory.language} value={language} onChange={setLanguage}><option value="">{copy.directory.allLanguages}</option>{PUBLIC_LANGUAGES.map((item) => <option key={item.code} value={item.code}>{languageName(item.code, locale)}</option>)}</Filter>
    </div></section>
    <section className={`${SHELL} py-12 sm:py-16`}>{filtered.length === 0 ? <p className="border-y border-[#d9d1c4] py-10 text-center text-[#5e675f]">{copy.directory.empty}</p> : <ul className="grid gap-x-10 gap-y-14 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((p) => <li key={p.slug}><a href={fineBinderyProfilePath(locale, p.slug)} className="group block">{p.imageUrl ? <img src={p.imageUrl} alt={p.workshopName} className="aspect-[4/3] w-full object-cover" /> : <div className="flex aspect-[4/3] items-center justify-center bg-[#dfe2d8] font-editorial text-5xl text-[#36513e]">{p.workshopName.slice(0, 1)}</div>}<p className="mt-5 text-xs font-semibold uppercase tracking-[0.14em] text-[#8a6235]">{p.city}, {countryName(p.countryCode, locale)}</p><h2 className="mt-2 font-editorial text-2xl text-[#17231c] group-hover:underline">{p.workshopName}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-[#59635b]">{p.bio}</p><p className="mt-4 text-sm text-[#36513e]">{p.skills.slice(0, 4).map((s) => specialtyName(s.slug, locale)).join(" · ")}</p></a></li>)}</ul>}</section>
  </main><FineBinderyFooter locale={locale} /></div>;
}

function Filter({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) {
  return <label className="text-xs font-semibold uppercase tracking-[0.14em] text-[#5e675f]">{label}<select className="mt-2 min-h-11 w-full border border-[#c9beae] bg-[#fffdf8] px-3 text-sm normal-case tracking-normal" value={value} onChange={(event) => onChange(event.target.value)}>{children}</select></label>;
}

export function FineBinderyWorkshopPage({ profile, locale }: { profile: NonNullable<PublicProfile>; locale: FineBinderyLocale }) {
  const copy = fineBinderyCopy(locale); useFineBinderyDocumentLocale(locale);
  const techniques = profile.techniqueKeys.map((key) => techniqueName(key, locale)); const materials = profile.materialKeys.map((key) => techniqueName(key, locale));
  return <div className="mr-site flex min-h-screen flex-col bg-[#f7f3eb] text-[#243128]"><FineBinderyHeader locale={locale} /><main className="flex-1">
    <section className={`${SHELL} grid gap-10 py-12 sm:py-20 lg:grid-cols-12 lg:items-center`}><div className="lg:col-span-6"><p className="mr-eyebrow text-[#8a6235]">{copy.profile.workshop} · {profile.city}, {countryName(profile.countryCode, locale)}</p><h1 className="mr-title mt-5 text-5xl leading-[0.98] text-[#17231c] sm:text-7xl">{profile.workshopName}</h1><p className="mt-5 text-lg text-[#59635b]">{profile.professionalName}</p><p className="mr-lead mt-7 max-w-xl">{profile.bio}</p>{locale !== "fr" && <p className="mt-3 text-xs italic text-[#6c756e]">{copy.common.originalText}</p>}<div className="mt-9"><FineBinderyIntakeCta locale={locale} slug={profile.slug} /></div></div><div className="lg:col-span-6">{profile.workshopPhotoUrl ? <img src={profile.workshopPhotoUrl} alt={profile.workshopName} className="aspect-[4/3] w-full object-cover" /> : <div className="flex aspect-[4/3] items-center justify-center bg-[#dfe2d8] font-editorial text-7xl text-[#36513e]">{profile.workshopName.slice(0, 1)}</div>}</div></section>
    <section className="border-y border-[#d9d1c4] bg-[#efe9de]"><div className={`${SHELL} grid gap-8 py-10 sm:grid-cols-3`}><Info title={copy.profile.specialties}>{profile.skills.map((s) => specialtyName(s.slug, locale)).join(" · ")}</Info><Info title={copy.profile.languages}>{profile.languages.map((code) => languageName(code, locale)).join(" · ")}</Info><Info title={copy.profile.techniques}>{[...techniques, ...materials].join(" · ") || copy.profile.according}</Info></div></section>
    {(profile.training || profile.philosophy) && <section className={`${SHELL} grid gap-10 py-14 sm:py-20 lg:grid-cols-2`}>{profile.training && <Info title={copy.profile.training}>{profile.training}</Info>}{profile.philosophy && <Info title={copy.profile.approach}>{profile.philosophy}</Info>}</section>}
    {profile.portfolio.length > 0 && <section className="bg-[#17231c] text-[#f7f3eb]"><div className={`${SHELL} py-14 sm:py-20`}><p className="mr-eyebrow text-[#c9a979]">{copy.profile.portfolio}</p><h2 className="mr-title mt-4 text-4xl sm:text-5xl">{copy.profile.work}</h2><div className="mt-10 grid gap-10 sm:grid-cols-2">{profile.portfolio.map((item) => <article key={item.id}><div className={`grid gap-1 ${item.beforePhotoUrl && item.afterPhotoUrl ? "grid-cols-2" : "grid-cols-1"}`}>{item.beforePhotoUrl && <figure><img src={item.beforePhotoUrl} alt={item.title} className="aspect-[4/3] w-full object-cover" /><figcaption className="mt-2 text-xs uppercase tracking-[0.12em] text-[#c9c4b8]">{copy.profile.before}</figcaption></figure>}{item.afterPhotoUrl && <figure><img src={item.afterPhotoUrl} alt={item.title} className="aspect-[4/3] w-full object-cover" /><figcaption className="mt-2 text-xs uppercase tracking-[0.12em] text-[#c9c4b8]">{copy.profile.after}</figcaption></figure>}</div><h3 className="mt-5 font-editorial text-2xl">{item.title}{item.year ? ` · ${item.year}` : ""}</h3>{item.description && <p className="mt-3 leading-7 text-[#d9d5cc]">{item.description}</p>}</article>)}</div></div></section>}
    <section className={`${SHELL} py-14 text-center sm:py-20`}><p className="mr-eyebrow text-[#8a6235]">{copy.profile.finalEyebrow}</p><h2 className="mr-title mx-auto mt-4 max-w-2xl text-4xl text-[#17231c] sm:text-5xl">{copy.profile.finalTitle(profile.workshopName)}</h2><div className="mt-8"><FineBinderyIntakeCta locale={locale} slug={profile.slug} /></div><div className="mt-8 flex flex-wrap justify-center gap-6 text-sm text-[#59635b]">{profile.websiteUrl && <a href={profile.websiteUrl} rel="noreferrer" className="underline">{copy.profile.website}</a>}{profile.instagramUrl && <a href={profile.instagramUrl} rel="noreferrer" className="underline">Instagram</a>}{profile.professionalPhone && <a href={`tel:${profile.professionalPhone}`} className="underline">{copy.profile.call}</a>}{profile.professionalEmail && <a href={`mailto:${profile.professionalEmail}`} className="underline">{copy.profile.email}</a>}</div></section>
  </main><FineBinderyFooter locale={locale} /></div>;
}

function Info({ title, children }: { title: string; children: React.ReactNode }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#8a6235]">{title}</p><p className="mt-3 whitespace-pre-line leading-7">{children}</p></div>; }

export function FineBinderyWorkshopNotFound({ locale }: { locale: FineBinderyLocale }) { const copy = fineBinderyCopy(locale); useFineBinderyDocumentLocale(locale); return <div className="mr-site flex min-h-screen flex-col bg-[#f7f3eb] text-[#243128]"><FineBinderyHeader locale={locale} /><main className={`${SHELL} flex-1 py-24 text-center`}><h1 className="mr-title text-4xl">{copy.profile.notFound}</h1><p className="mt-4 text-[#59635b]">{copy.profile.notFoundBody}</p><a href={fineBinderyDirectoryPath(locale)} className="mt-8 inline-flex min-h-11 items-center underline">{copy.profile.back}</a></main><FineBinderyFooter locale={locale} /></div>; }

export const FINE_BINDERY_PUBLIC_REFERENCE_COUNTS = { languages: PUBLIC_LANGUAGES.length, techniques: PUBLIC_TECHNIQUES.length, materials: PUBLIC_MATERIALS.length } as const;
