import { en } from "./en";
import type { FineBinderyPublicCopy } from "./types";

export const de: FineBinderyPublicCopy = {
  ...en,
  seo: { homeTitle: "Fine Bindery — Französische Buchbindekunst", homeDescription: "Buchbinder und Buchrestauratoren in Frankreich mit einer internationalen Ansprechperson für Ihr Projekt.", directoryTitle: "Buchbinder und Buchrestauratoren in Frankreich — Fine Bindery", directoryDescription: "Entdecken Sie unabhängige französische Werkstätten für Buchbinderei, Restaurierung, Konservierung und Vergoldung.", profileTitle: (w) => `${w} — Buchbinderei und Restaurierung | Fine Bindery`, profileDescription: (w, c) => `Entdecken Sie ${w}, eine unabhängige Buchbinder- und Restaurierungswerkstatt in ${c}, Frankreich.` },
  nav: { how: "So funktioniert es", services: "Leistungen", workshops: "Werkstätten", faq: "Fragen", signIn: "Anmelden", language: "Sprache" },
  common: { start: "Projekt anfragen", project: "Projekt", france: "Frankreich", skills: "Fachgebiete", languages: "Sprachen", techniques: "Techniken und Materialien", originalText: "Werkstatttext in der Originalsprache." },
  footer: { summary: "Das internationale Netzwerk für französische Buchbinderei und Buchkonservierung.", information: "Informationen", legal: "Impressum", privacy: "Datenschutz", terms: "Nutzungsbedingungen", sales: "Verkaufsbedingungen", closing: "Französische Buchbinderei, Restaurierung und Handwerkskunst unabhängiger Ateliers." },
  home: { ...en.home,
    eyebrow: "Französisches Handwerk, persönlich koordiniert", title: "Wir übernehmen die Verantwortung für den gesamten Weg Ihres Buches.", lead: "Vom ersten Gespräch bis zur sicheren Rückkehr koordiniert eine Fine-Bindery-Ansprechperson die passende unabhängige Werkstatt, alle Entscheidungen und den internationalen Transport.", discover: "Französisches Handwerk entdecken", proof: "Eine feste Ansprechperson · Ausgewählte französische Werkstätten · Weltweite Koordination",
    benefitsEyebrow: "Ihr Buch. Die richtigen Hände.", benefitsTitle: "Wir wählen die Werkstatt nach Buch, Technik und Projekt aus – ohne Preiswettbewerb.", benefitsLead: "Fine Bindery arbeitet mit unabhängigen Buchbindern, Vergoldern und Restauratoren mit ausgewiesenen Fachgebieten.", benefits: [ { title: "Ein verstandenes Projekt", body: "Sie beschreiben Ihr Buch einmal. Fine Bindery prüft die erforderlichen Arbeiten vor einem Vorschlag." }, { title: "Ein verlässlicher Preis", body: "Ein Festpreis bei klarer Beurteilung oder ein bestätigter Kostenrahmen vor dem Versand." }, { title: "Die passende Werkstatt", body: "Ihr Projekt geht an die Werkstatt mit den passenden Fähigkeiten." }, { title: "Eine Ansprechperson", body: "Fine Bindery begleitet das Projekt vom ersten Foto bis zur Rückkehr." } ],
    offersEyebrow: "Leistungen", offersTitle: "Vier Wege, uns Ihr Buch anzuvertrauen.", photoCredit: "Fotografien", offers: [ { title: "Künstlerischer Bucheinband", body: "Traditionelle und zeitgenössische Einbände aus Leder, Gewebe und ausgewählten Materialien." }, { title: "Buchrestaurierung", body: "Sorgfältige Restaurierung und Konservierung alter, wertvoller oder persönlich bedeutender Bücher." }, { title: "Neueinband für Sammler", body: "Eine besondere Ausgabe in ein einzigartiges Objekt verwandeln." }, { title: "Individuelle Anfertigungen", body: "Unikate, Präsentations- und Familienbücher, Kassetten und besondere Projekte." } ],
    howEyebrow: "So funktioniert es", howTitle: "Von Ihnen in eine französische Werkstatt – und zurück.", steps: ["Buch vorstellen", "Vorschlag erhalten", "Passende Werkstatt auswählen", "Buch nach Frankreich senden", "Handwerk verfolgen", "Buch zurückerhalten"],
    workshopsEyebrow: "Hinter jedem Buch steht französisches Handwerk", workshopsTitle: "Unabhängige Buchbinder, Restauratoren und Vergolder in Frankreich.", workshopsLead: "Jedes Projekt wird nach den benötigten Fähigkeiten vergeben.", selected: "Für das Fine-Bindery-Netzwerk ausgewählt.", discoverWorkshops: "Veröffentlichte Werkstätten entdecken",
    trustEyebrow: "Ihr Buch reist", trustTitle: "Ihr Buch reist. Seine Geschichte geht nicht verloren.", trust: ["Zustand dokumentiert", "Persönliche Koordination", "Ausgewählte Werkstatt", "Nachverfolgter internationaler Weg"],
    shippingEyebrow: "Ihr Buch nach Frankreich bringen", shippingTitle: "Sicherer internationaler Versand, passend zum Buch.", shippingLead: "Fine Bindery organisiert den Weg nach Art und Wert des Buches. Der Versand wird separat berechnet.",
    faqEyebrow: "Antworten auf Ihre Fragen", faqTitle: "Vor dem Start.", faq: [ { question: "Muss ich Französisch sprechen?", answer: "Nein. Fine Bindery bleibt während des gesamten Projekts Ihre Ansprechperson." }, { question: "Wie wird die Werkstatt ausgewählt?", answer: "Nach Buch, erforderlichen Techniken, Komplexität und Verfügbarkeit." }, { question: "Ist der Versand enthalten?", answer: "Nein. Er wird je nach Ziel, Wert und erforderlicher Sorgfalt separat berechnet." }, { question: "Können Sie wertvolle oder alte Bücher betreuen?", answer: "Ja, nach individueller Prüfung und mit geeigneter Logistik." } ],
    finalTitle: "Ihr Buch verdient die richtigen Hände.", finalLead: "Von den ersten Fotos bis zur Rückkehr koordiniert Fine Bindery den gesamten Weg zu einer ausgewählten französischen Werkstatt.", established: "gegründet",
  },
  directory: { eyebrow: "FineBindery-Netzwerk · Frankreich", title: "Werkstätten, ausgewählt nach Handwerk, Erfahrung und Haltung.", lead: "Entdecken Sie unabhängige Buchbinder und Restauratoren. Eine Anfrage von einer Werkstattseite erreicht diese Werkstatt direkt.", country: "Land", specialty: "Fachgebiet", language: "Sprache", allCountries: "Alle Länder", allSpecialties: "Alle Fachgebiete", allLanguages: "Alle Sprachen", empty: "Keine veröffentlichte Werkstatt entspricht diesen Filtern." },
  profile: { workshop: "FineBindery-Werkstatt", discuss: "Projekt anfragen", specialties: "Fachgebiete", languages: "Sprachen", techniques: "Techniken und Materialien", according: "Je nach Projekt", training: "Ausbildung und Erfahrung", approach: "Arbeitsweise", portfolio: "Ausgewählte Arbeiten", work: "Arbeiten der Werkstatt.", before: "Vorher", after: "Nachher", finalEyebrow: "Ein Buch, ein Gespräch, das passende Handwerk", finalTitle: (w) => `Besprechen Sie Ihr Projekt direkt mit ${w}.`, website: "Website der Werkstatt", call: "Werkstatt anrufen", email: "E-Mail an die Werkstatt", notFound: "Werkstatt nicht gefunden", notFoundBody: "Diese Seite ist nicht veröffentlicht oder nicht mehr vorhanden.", back: "Fachbetriebe entdecken" },
};
