import { en } from "./en";
import type { FineBinderyPublicCopy } from "./types";

export const es: FineBinderyPublicCopy = {
  ...en,
  seo: { homeTitle: "Fine Bindery — Encuadernación artística francesa", homeDescription: "Encuadernadores y restauradores de libros en Francia, con un único interlocutor internacional para tu proyecto.", directoryTitle: "Encuadernadores y restauradores de libros en Francia — Fine Bindery", directoryDescription: "Descubre talleres franceses independientes de encuadernación, restauración, conservación y dorado.", profileTitle: (w) => `${w} — Encuadernación y restauración | Fine Bindery`, profileDescription: (w, c) => `Descubre ${w}, taller independiente de encuadernación y restauración en ${c}, Francia.` },
  nav: { how: "Cómo funciona", services: "Servicios", workshops: "Talleres", faq: "Preguntas", signIn: "Acceder", language: "Idioma" },
  common: { start: "Presenta tu proyecto", project: "Proyecto", france: "Francia", skills: "Especialidades", languages: "Idiomas", techniques: "Técnicas y materiales", originalText: "Texto del taller mostrado en su idioma original." },
  footer: { summary: "La red internacional de encuadernación y conservación del libro en Francia.", information: "Información", legal: "Aviso legal", privacy: "Privacidad", terms: "Condiciones de uso", sales: "Condiciones de venta", closing: "Encuadernación, restauración y artesanía francesa por talleres independientes." },
  home: { ...en.home,
    eyebrow: "Artesanía francesa, coordinada personalmente", title: "Nos responsabilizamos de todo el recorrido de tu libro.", lead: "Desde la primera conversación hasta su regreso seguro, una persona de Fine Bindery coordina el taller francés adecuado, las decisiones y el transporte internacional.", discover: "Descubre la artesanía francesa", proof: "Un interlocutor responsable · Talleres franceses seleccionados · Coordinación internacional",
    benefitsEyebrow: "Tu libro. Las manos adecuadas.", benefitsTitle: "Elegimos el taller según el libro, la técnica y el proyecto, sin pujas entre talleres.", benefitsLead: "Fine Bindery colabora con encuadernadores, doradores y restauradores independientes seleccionados por sus especialidades.", benefits: [ { title: "Un proyecto comprendido", body: "Describe tu libro una sola vez. Fine Bindery estudia el trabajo antes de proponer nada." }, { title: "Un precio claro", body: "Precio fijo cuando el proyecto puede evaluarse, o estimación confirmada antes del envío." }, { title: "El taller adecuado", body: "El proyecto llega al taller con las competencias necesarias." }, { title: "Un solo interlocutor", body: "Fine Bindery acompaña el proyecto desde la primera foto hasta el regreso del libro." } ],
    offersEyebrow: "Servicios", offersTitle: "Cuatro formas de confiarnos tu libro.", photoCredit: "Fotografías", offers: [ { title: "Encuadernación artística", body: "Encuadernaciones tradicionales y contemporáneas en piel, tela y materiales selectos." }, { title: "Restauración de libros", body: "Restauración y conservación cuidadosas de libros antiguos, valiosos o significativos." }, { title: "Reencuadernación de colección", body: "Transforma una edición querida o de colección en una pieza única." }, { title: "Creaciones a medida", body: "Encuadernaciones únicas, libros de presentación y familiares, estuches y proyectos especiales." } ],
    howEyebrow: "Cómo funciona", howTitle: "De tu casa a un taller francés, y de vuelta.", steps: ["Presenta tu libro", "Recibe la propuesta", "Elegimos el taller adecuado", "El libro viaja a Francia", "Sigue el trabajo artesanal", "Recibe el libro en casa"],
    workshopsEyebrow: "Detrás de cada libro, un artesano francés", workshopsTitle: "Encuadernadores, restauradores y doradores independientes en Francia.", workshopsLead: "Cada proyecto se confía según las competencias que necesita.", selected: "Seleccionado para la red Fine Bindery.", discoverWorkshops: "Descubre los talleres publicados",
    trustEyebrow: "Tu libro viaja", trustTitle: "Tu libro viaja. Su historia no se pierde.", trust: ["Estado documentado", "Coordinación personal", "Taller seleccionado", "Trayecto internacional con seguimiento"],
    shippingEyebrow: "Llevar tu libro a Francia", shippingTitle: "Envío internacional seguro y adaptado al libro.", shippingLead: "Fine Bindery organiza el trayecto según la naturaleza y el valor del libro. El envío se presupuesta por separado.",
    faqEyebrow: "Tus preguntas", faqTitle: "Antes de empezar.", faq: [ { question: "¿Necesito hablar francés?", answer: "No. Fine Bindery sigue siendo tu interlocutor durante todo el proyecto." }, { question: "¿Cómo se elige el taller?", answer: "Según el libro, las técnicas necesarias, la complejidad y la disponibilidad." }, { question: "¿Está incluido el envío?", answer: "No. Se presupuesta por separado según destino, valor y nivel de cuidado." }, { question: "¿Trabajáis con libros antiguos o valiosos?", answer: "Sí, tras una evaluación individual y con una logística adecuada." } ],
    finalTitle: "Tu libro merece las manos adecuadas.", finalLead: "Desde las primeras fotografías hasta su regreso, Fine Bindery coordina todo el recorrido hacia un taller francés seleccionado.", established: "fundado en",
  },
  directory: { eyebrow: "Red FineBindery · Francia", title: "Talleres elegidos por su oficio, trayectoria y sensibilidad.", lead: "Descubre encuadernadores y restauradores independientes. Una solicitud desde la página de un taller llega directamente a ese taller.", country: "País", specialty: "Especialidad", language: "Idioma", allCountries: "Todos los países", allSpecialties: "Todas las especialidades", allLanguages: "Todos los idiomas", empty: "Ningún taller publicado coincide con estos filtros." },
  profile: { workshop: "Taller FineBindery", discuss: "Presenta tu proyecto", specialties: "Especialidades", languages: "Idiomas", techniques: "Técnicas y materiales", according: "Según el proyecto", training: "Formación y experiencia", approach: "Enfoque", portfolio: "Trabajos seleccionados", work: "El trabajo del taller.", before: "Antes", after: "Después", finalEyebrow: "Un libro, una conversación, el oficio adecuado", finalTitle: (w) => `Habla de tu proyecto directamente con ${w}.`, website: "Web del taller", call: "Llamar al taller", email: "Escribir al taller", notFound: "Taller no encontrado", notFoundBody: "Esta página no está publicada o ya no existe.", back: "Descubre los profesionales" },
};
