import { en } from "./en";
import type { FineBinderyPublicCopy } from "./types";

export const fr: FineBinderyPublicCopy = {
  ...en,
  seo: { homeTitle: "Fine Bindery — Reliure d’art française", homeDescription: "Relieurs et restaurateurs de livres en France, avec un interlocuteur international unique pour votre projet.", directoryTitle: "Relieurs et restaurateurs de livres en France — Fine Bindery", directoryDescription: "Découvrez des ateliers français indépendants de reliure, restauration, conservation et dorure.", profileTitle: (w) => `${w} — Reliure et restauration | Fine Bindery`, profileDescription: (w, c) => `Découvrez ${w}, atelier indépendant de reliure et de conservation à ${c}, France.` },
  nav: { how: "Comment ça marche", services: "Nos savoir-faire", workshops: "Les ateliers", faq: "Questions", signIn: "Se connecter", language: "Langue" },
  common: { start: "Présenter mon projet", project: "Projet", france: "France", skills: "Savoir-faire", languages: "Langues", techniques: "Techniques et matières", originalText: "Texte de l’atelier affiché dans sa langue d’origine." },
  footer: { summary: "Le réseau international de la reliure et de la conservation du livre en France.", information: "Informations", legal: "Mentions légales", privacy: "Confidentialité", terms: "Conditions d’utilisation", sales: "Conditions de vente", closing: "Reliure, restauration et métiers du livre en France, par des artisans indépendants." },
  home: { ...en.home,
    eyebrow: "Le savoir-faire français, personnellement coordonné", title: "Nous prenons en charge tout le parcours de votre livre.", lead: "Du premier échange à son retour, un interlocuteur Fine Bindery coordonne l’atelier français adapté, les décisions et le transport international.", discover: "Découvrir les savoir-faire français", proof: "Un interlocuteur responsable · Des ateliers français choisis · Une coordination internationale",
    benefitsEyebrow: "Votre livre. Les bons gestes.", benefitsTitle: "Nous choisissons l’atelier selon le livre, la technique et le projet, sans mise en concurrence.", benefitsLead: "Fine Bindery réunit des relieurs, doreurs et restaurateurs indépendants choisis pour leurs savoir-faire.", benefits: [
      { title: "Un projet compris", body: "Vous décrivez votre livre une fois. Fine Bindery étudie le travail avant toute proposition." }, { title: "Un prix lisible", body: "Un prix fixe quand le projet peut être évalué, ou une estimation confirmée avant l’envoi du livre." }, { title: "Le bon atelier", body: "Votre projet rejoint l’atelier dont les compétences lui correspondent." }, { title: "Un seul interlocuteur", body: "Fine Bindery suit le projet de la première photo jusqu’au retour du livre." },
    ],
    offersEyebrow: "Nos savoir-faire", offersTitle: "Quatre façons de nous confier votre livre.", photoCredit: "Photographies", offers: [
      { title: "Reliure d’art", body: "Reliures traditionnelles et contemporaines en cuir, toile et matières choisies." }, { title: "Restauration du livre", body: "Restauration et conservation attentives de livres anciens, précieux ou affectifs." }, { title: "Nouvelle reliure de collection", body: "Transformer une édition aimée ou de collection en pièce unique." }, { title: "Créations sur mesure", body: "Reliures uniques, livres de présentation, livres de famille, étuis et projets d’exception." },
    ],
    howEyebrow: "Comment ça marche", howTitle: "De chez vous à un atelier français, puis de retour.", steps: ["Présentez votre livre", "Recevez notre proposition", "Nous choisissons le bon atelier", "Votre livre rejoint la France", "Suivez le travail", "Recevez votre livre chez vous"],
    workshopsEyebrow: "Derrière chaque livre, un artisan français", workshopsTitle: "Des relieurs, restaurateurs et doreurs indépendants partout en France.", workshopsLead: "Chaque projet est confié selon les savoir-faire nécessaires.", selected: "Atelier sélectionné pour le réseau Fine Bindery.", discoverWorkshops: "Découvrir les ateliers publiés",
    trustEyebrow: "Votre livre voyage", trustTitle: "Votre livre voyage. Son histoire ne se perd pas.", trust: ["État documenté", "Coordination personnelle", "Atelier français choisi", "Parcours international suivi"],
    shippingEyebrow: "Faire venir votre livre en France", shippingTitle: "Un transport international sécurisé, adapté au livre.", shippingLead: "Fine Bindery organise le parcours selon la nature et la valeur du livre. Le transport fait l’objet d’un prix séparé.",
    faqEyebrow: "Vos questions", faqTitle: "Avant de commencer.", faq: [ { question: "Dois-je parler français ?", answer: "Non. Fine Bindery reste votre interlocuteur pendant tout le projet." }, { question: "Comment l’atelier est-il choisi ?", answer: "Selon le livre, les techniques nécessaires, la complexité du projet et les disponibilités." }, { question: "Le transport est-il inclus ?", answer: "Non. Il est chiffré séparément selon la destination, la valeur et le niveau de précaution." }, { question: "Prenez-vous en charge les livres anciens ou précieux ?", answer: "Oui, après étude individuelle et validation d’une logistique adaptée." } ],
    finalTitle: "Votre livre mérite les bons gestes.", finalLead: "Des premières photographies à son retour, Fine Bindery coordonne tout le parcours vers un atelier français choisi.", established: "fondé en",
  },
  directory: { eyebrow: "Réseau FineBindery · France", title: "Des ateliers choisis pour leur geste, leur parcours et leur regard.", lead: "Découvrez des relieurs et restaurateurs indépendants. Un projet présenté depuis une page atelier arrive directement dans cet atelier.", country: "Pays", specialty: "Spécialité", language: "Langue", allCountries: "Tous les pays", allSpecialties: "Toutes les spécialités", allLanguages: "Toutes les langues", empty: "Aucun atelier publié ne correspond à ces critères." },
  profile: { workshop: "Atelier FineBindery", discuss: "Présenter mon projet", specialties: "Spécialités", languages: "Langues", techniques: "Techniques et matières", according: "Selon le projet", training: "Parcours", approach: "Approche", portfolio: "Réalisations", work: "Le travail de l’atelier.", before: "Avant", after: "Après", finalEyebrow: "Un livre, un échange, un geste juste", finalTitle: (w) => `Parlez directement de votre projet à ${w}.`, website: "Site de l’atelier", call: "Téléphoner à l’atelier", email: "Écrire à l’atelier", notFound: "Atelier introuvable", notFoundBody: "Cette page n’est pas publiée ou n’existe plus.", back: "Découvrir les professionnels" },
};
