import { en } from "./en";
import type { FineBinderyPublicCopy } from "./types";

export const it: FineBinderyPublicCopy = {
  ...en,
  seo: { homeTitle: "Fine Bindery — Legatoria d’arte francese", homeDescription: "Legatori e restauratori di libri in Francia, con un unico referente internazionale per il tuo progetto.", directoryTitle: "Legatori e restauratori di libri in Francia — Fine Bindery", directoryDescription: "Scopri laboratori francesi indipendenti di legatoria, restauro, conservazione e doratura.", profileTitle: (w) => `${w} — Legatoria e restauro | Fine Bindery`, profileDescription: (w, c) => `Scopri ${w}, laboratorio indipendente di legatoria e restauro a ${c}, Francia.` },
  nav: { how: "Come funziona", services: "Servizi", workshops: "Laboratori", faq: "Domande", signIn: "Accedi", language: "Lingua" },
  common: { start: "Presenta il tuo progetto", project: "Progetto", france: "Francia", skills: "Specialità", languages: "Lingue", techniques: "Tecniche e materiali", originalText: "Testo del laboratorio mostrato nella lingua originale." },
  footer: { summary: "La rete internazionale della legatoria e conservazione del libro in Francia.", information: "Informazioni", legal: "Note legali", privacy: "Privacy", terms: "Condizioni d’uso", sales: "Condizioni di vendita", closing: "Legatoria, restauro e artigianato francese realizzati da laboratori indipendenti." },
  home: { ...en.home,
    eyebrow: "Artigianato francese, coordinato personalmente", title: "Ci assumiamo la responsabilità dell’intero viaggio del tuo libro.", lead: "Dal primo colloquio al ritorno in sicurezza, un referente Fine Bindery coordina il laboratorio francese più adatto, le decisioni e il trasporto internazionale.", discover: "Scopri l’artigianato francese", proof: "Un referente responsabile · Laboratori francesi selezionati · Coordinamento internazionale",
    benefitsEyebrow: "Il tuo libro. Le mani giuste.", benefitsTitle: "Scegliamo il laboratorio in base al libro, alla tecnica e al progetto, senza gare al ribasso.", benefitsLead: "Fine Bindery collabora con legatori, doratori e restauratori indipendenti selezionati per le loro competenze.", benefits: [ { title: "Un progetto compreso", body: "Descrivi il libro una sola volta. Fine Bindery valuta il lavoro prima di qualsiasi proposta." }, { title: "Un prezzo chiaro", body: "Un prezzo fisso quando il progetto è valutabile, oppure una stima confermata prima della spedizione." }, { title: "Il laboratorio giusto", body: "Il progetto arriva al laboratorio con le competenze adatte." }, { title: "Un solo referente", body: "Fine Bindery segue il progetto dalla prima foto fino al ritorno del libro." } ],
    offersEyebrow: "Servizi", offersTitle: "Quattro modi per affidarci il tuo libro.", photoCredit: "Fotografie", offers: [ { title: "Legatura d’arte", body: "Legature tradizionali e contemporanee in pelle, tela e materiali pregiati." }, { title: "Restauro del libro", body: "Restauro e conservazione accurati di libri antichi, preziosi o importanti per te." }, { title: "Rilegatura da collezione", body: "Trasforma un’edizione amata o da collezione in un oggetto unico." }, { title: "Creazioni su misura", body: "Legature uniche, libri di presentazione e di famiglia, custodie e progetti speciali." } ],
    howEyebrow: "Come funziona", howTitle: "Da casa tua a un laboratorio francese, e ritorno.", steps: ["Presenta il tuo libro", "Ricevi la proposta", "Selezioniamo il laboratorio", "Il libro viaggia in Francia", "Segui la lavorazione", "Ricevi il libro a casa"],
    workshopsEyebrow: "Dietro ogni libro, un artigiano francese", workshopsTitle: "Legatori, restauratori e doratori indipendenti in tutta la Francia.", workshopsLead: "Ogni progetto viene affidato secondo le competenze necessarie.", selected: "Selezionato per la rete Fine Bindery.", discoverWorkshops: "Scopri i laboratori pubblicati",
    trustEyebrow: "Il tuo libro viaggia", trustTitle: "Il tuo libro viaggia. La sua storia non si perde.", trust: ["Stato documentato", "Coordinamento personale", "Laboratorio selezionato", "Viaggio internazionale tracciato"],
    shippingEyebrow: "Portare il libro in Francia", shippingTitle: "Spedizione internazionale sicura, adatta al libro.", shippingLead: "Fine Bindery organizza il viaggio secondo natura e valore del libro. La spedizione è quotata separatamente.",
    faqEyebrow: "Le tue domande", faqTitle: "Prima di iniziare.", faq: [ { question: "Devo parlare francese?", answer: "No. Fine Bindery resta il tuo referente per tutto il progetto." }, { question: "Come viene scelto il laboratorio?", answer: "In base al libro, alle tecniche necessarie, alla complessità e alla disponibilità." }, { question: "La spedizione è inclusa?", answer: "No. È quotata separatamente in base a destinazione, valore e livello di cura." }, { question: "Potete occuparvi di libri antichi o preziosi?", answer: "Sì, dopo una valutazione individuale e con una logistica adeguata." } ],
    finalTitle: "Il tuo libro merita le mani giuste.", finalLead: "Dalle prime fotografie al ritorno a casa, Fine Bindery coordina l’intero percorso verso un laboratorio francese selezionato.", established: "fondato nel",
  },
  directory: { eyebrow: "Rete FineBindery · Francia", title: "Laboratori scelti per tecnica, esperienza e sensibilità.", lead: "Scopri legatori e restauratori indipendenti. Una richiesta inviata dalla pagina di un laboratorio arriva direttamente a quel laboratorio.", country: "Paese", specialty: "Specialità", language: "Lingua", allCountries: "Tutti i paesi", allSpecialties: "Tutte le specialità", allLanguages: "Tutte le lingue", empty: "Nessun laboratorio pubblicato corrisponde ai filtri." },
  profile: { workshop: "Laboratorio FineBindery", discuss: "Presenta il tuo progetto", specialties: "Specialità", languages: "Lingue", techniques: "Tecniche e materiali", according: "Secondo il progetto", training: "Formazione ed esperienza", approach: "Approccio", portfolio: "Lavori selezionati", work: "Il lavoro del laboratorio.", before: "Prima", after: "Dopo", finalEyebrow: "Un libro, un dialogo, il gesto giusto", finalTitle: (w) => `Parla del tuo progetto direttamente con ${w}.`, website: "Sito del laboratorio", call: "Chiama il laboratorio", email: "Scrivi al laboratorio", notFound: "Laboratorio non trovato", notFoundBody: "Questa pagina non è pubblicata o non esiste più.", back: "Scopri i professionisti" },
};
