import { createClient } from "@supabase/supabase-js";
const url = process.env.SUPABASE_URL!;
const sb = createClient(url, process.env.SUPABASE_SERVICE_ROLE_KEY!);
const email = "test-billing-sandbox@metre-pro-test.com";
const { data, error } = await sb.auth.admin.generateLink({ type: "magiclink", email });
if (error) throw error;
const pub = createClient(url, process.env.SUPABASE_PUBLISHABLE_KEY ?? "sb_publishable_0h5L1iNw9Zm_PfAWd3kE0A_tLDuD09P", { auth: { persistSession: false } });
const v = await pub.auth.verifyOtp({ type: "magiclink", token_hash: data.properties.hashed_token });
if (v.error) throw v.error;
await Bun.write("/tmp/br/session.json", JSON.stringify(v.data.session));
console.log("ok session for", v.data.user?.email, "expires", v.data.session?.expires_at);
