import type { FineBinderyLocale } from "@/marketplace/i18n/fineBinderyLocale";
export const workshopIntakeCopy = {
  fr: {
    title: "Votre demande à cet atelier", intro: "Votre projet est adressé à l’atelier dont vous avez suivi le lien. Il établit votre devis et vous facture directement. Oppe fournit l’outil et le suivi.",
    review: "Envoyer votre demande ne vous engage à rien. Aucun paiement ni envoi du livre maintenant. Vous convenez du prix, du paiement et du transport avec cet atelier avant de vous engager.",
    next: "Votre demande est enregistrée pour cet atelier. Il vous répondra et établira votre devis. Vous pourrez suivre votre dossier dans votre espace. N’envoyez pas le livre avant d’avoir convenu du transport avec lui.",
    book: "Ces informations permettent à cet atelier d’étudier votre ouvrage et de préparer votre devis.",
    budget: "Budget indicatif : cet atelier fixera le prix après étude du travail demandé.",
    contact: "Ces coordonnées permettent à cet atelier de vous répondre et de vous présenter son devis. Elles lui sont transmises avec votre demande.",
    consent: "J’accepte que l’atelier dont j’ai suivi le lien reçoive ma demande et mes coordonnées pour me répondre. Oppe fournit l’outil de transmission et de suivi.",
    location: "La ville suffit à cette étape. Vous conviendrez ensuite des adresses de transport avec cet atelier.",
  },
  en: {
    title: "Your request to this workshop", intro: "Your project goes to the workshop whose link you followed. The workshop prepares your quote and invoices you directly. Oppe provides the software and tracking.",
    review: "Sending your request does not commit you. There is no payment or book shipment now. Agree on the price, payment and transport with this workshop before committing.",
    next: "Your request has been recorded for this workshop. It will reply and prepare your quote. You can follow your case in your account. Do not send the book until transport has been agreed with the workshop.",
    book: "This information helps this workshop assess your book and prepare your quote.",
    budget: "Indicative budget: this workshop will set the price after assessing the requested work.",
    contact: "These contact details let this workshop reply and present its quote. They are sent to the workshop with your request.",
    consent: "I agree to the workshop whose link I followed receiving my request and contact details so it can reply. Oppe provides the submission and tracking software.",
    location: "The city is enough at this stage. Agree transport addresses with this workshop later.",
  },
  de: {
    title: "Ihre Anfrage an diese Werkstatt", intro: "Ihr Projekt geht an die Werkstatt, deren Link Sie gefolgt sind. Sie erstellt Ihr Angebot und stellt Ihnen direkt die Rechnung. Oppe stellt die Software und die Nachverfolgung bereit.",
    review: "Ihre Anfrage verpflichtet Sie zu nichts. Jetzt erfolgen weder Zahlung noch Buchversand. Vereinbaren Sie Preis, Zahlung und Transport mit dieser Werkstatt, bevor Sie sich verpflichten.",
    next: "Ihre Anfrage wurde für diese Werkstatt gespeichert. Sie wird antworten und Ihr Angebot erstellen. Sie können Ihren Vorgang in Ihrem Konto verfolgen. Versenden Sie das Buch erst nach Vereinbarung des Transports mit der Werkstatt.",
    book: "Diese Angaben helfen dieser Werkstatt, Ihr Buch zu prüfen und Ihr Angebot zu erstellen.",
    budget: "Unverbindliches Budget: Diese Werkstatt legt den Preis nach Prüfung der gewünschten Arbeiten fest.",
    contact: "Diese Kontaktdaten ermöglichen dieser Werkstatt, Ihnen zu antworten und ihr Angebot vorzulegen. Sie werden mit Ihrer Anfrage an die Werkstatt übermittelt.",
    consent: "Ich stimme zu, dass die Werkstatt, deren Link ich gefolgt bin, meine Anfrage und Kontaktdaten erhält, um mir zu antworten. Oppe stellt die Software zur Übermittlung und Nachverfolgung bereit.",
    location: "Der Ort reicht in diesem Schritt. Die Transportadressen vereinbaren Sie später mit dieser Werkstatt.",
  },
  it: {
    title: "La vostra richiesta a questo laboratorio", intro: "Il progetto viene inviato al laboratorio di cui avete seguito il link. Il laboratorio prepara il preventivo e vi fattura direttamente. Oppe fornisce il software e il monitoraggio.",
    review: "Inviare la richiesta non vi impegna. Nessun pagamento o invio del libro adesso. Concordate prezzo, pagamento e trasporto con questo laboratorio prima di impegnarvi.",
    next: "La richiesta è stata registrata per questo laboratorio. Vi risponderà e preparerà il preventivo. Potete seguire la pratica nel vostro spazio. Non inviate il libro prima di aver concordato il trasporto con il laboratorio.",
    book: "Queste informazioni aiutano questo laboratorio a esaminare il libro e preparare il preventivo.",
    budget: "Budget indicativo: questo laboratorio fisserà il prezzo dopo aver esaminato il lavoro richiesto.",
    contact: "Questi recapiti permettono al laboratorio di rispondervi e presentarvi il preventivo. Vengono trasmessi al laboratorio con la richiesta.",
    consent: "Accetto che il laboratorio di cui ho seguito il link riceva la richiesta e i miei recapiti per rispondermi. Oppe fornisce il software di trasmissione e monitoraggio.",
    location: "In questa fase basta la città. Concorderete poi gli indirizzi di trasporto con questo laboratorio.",
  },
  es: {
    title: "Su solicitud a este taller", intro: "Su proyecto se envía al taller cuyo enlace ha seguido. El taller prepara su presupuesto y le factura directamente. Oppe proporciona el software y el seguimiento.",
    review: "Enviar la solicitud no le compromete. Ahora no hay pago ni envío del libro. Acuerde el precio, el pago y el transporte con este taller antes de comprometerse.",
    next: "Su solicitud ha quedado registrada para este taller. Le responderá y preparará su presupuesto. Puede seguir el expediente en su espacio. No envíe el libro antes de acordar el transporte con el taller.",
    book: "Esta información ayuda a este taller a estudiar su libro y preparar su presupuesto.",
    budget: "Presupuesto orientativo: este taller fijará el precio después de estudiar el trabajo solicitado.",
    contact: "Estos datos permiten que este taller le responda y presente su presupuesto. Se envían al taller con su solicitud.",
    consent: "Acepto que el taller cuyo enlace he seguido reciba mi solicitud y mis datos de contacto para responderme. Oppe proporciona el software de envío y seguimiento.",
    location: "En este paso basta con la ciudad. Acordará después las direcciones de transporte con este taller.",
  },
} satisfies Record<FineBinderyLocale, Record<string, string>>;

