/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivateBetaRouteImport } from './routes/private-beta'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FreeInquiryAuditRouteImport } from './routes/free-inquiry-audit'
import { Route as ExampleProjectBriefRouteImport } from './routes/example-project-brief'
import { Route as DeckBuildersRouteImport } from './routes/deck-builders'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectSummaryAccessTokenRouteImport } from './routes/project-summary.$accessToken'
import { Route as MPublicTokenRouteImport } from './routes/m.$publicToken'
import { Route as DemoDeckProjectRouteImport } from './routes/demo.deck-project'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthenticatedBuildRouteRouteImport } from './routes/_authenticated/build/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedBuildIndexRouteImport } from './routes/_authenticated/build/index'
import { Route as ApiPublicTrackViewRouteImport } from './routes/api/public/track-view'
import { Route as ApiPublicProjectSummaryRouteImport } from './routes/api/public/project-summary'
import { Route as ApiPublicFaqAskRouteImport } from './routes/api/public/faq-ask'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicBuildRuntimeRouteImport } from './routes/api/public/build-runtime'
import { Route as ApiPublicBuildPublicIntakeRouteImport } from './routes/api/public/build-public-intake'
import { Route as ApiPublicAnalyzeSiteRouteImport } from './routes/api/public/analyze-site'
import { Route as AuthenticatedPortalTeamRouteImport } from './routes/_authenticated/portal/team'
import { Route as AuthenticatedPortalSetupRouteImport } from './routes/_authenticated/portal/setup'
import { Route as AuthenticatedPortalSettingsRouteImport } from './routes/_authenticated/portal/settings'
import { Route as AuthenticatedPortalMissionsRouteImport } from './routes/_authenticated/portal/missions'
import { Route as AuthenticatedPortalDemosRouteImport } from './routes/_authenticated/portal/demos'
import { Route as AuthenticatedPortalBillingRouteImport } from './routes/_authenticated/portal/billing'
import { Route as AuthenticatedBuildSettingsRouteImport } from './routes/_authenticated/build/settings'
import { Route as AuthenticatedBuildOnboardingRouteImport } from './routes/_authenticated/build/onboarding'
import { Route as AuthenticatedBuildMissionsRouteImport } from './routes/_authenticated/build/missions'
import { Route as AuthenticatedBuildKnowledgeRouteImport } from './routes/_authenticated/build/knowledge'
import { Route as AuthenticatedBuildDashboardRouteImport } from './routes/_authenticated/build/dashboard'
import { Route as AuthenticatedBuildActivityRouteImport } from './routes/_authenticated/build/activity'
import { Route as AuthenticatedBuildWorkspacesIndexRouteImport } from './routes/_authenticated/build/workspaces.index'
import { Route as AuthenticatedBuildRequestsIndexRouteImport } from './routes/_authenticated/build/requests.index'
import { Route as AuthenticatedBuildPlaybooksIndexRouteImport } from './routes/_authenticated/build/playbooks.index'
import { Route as AuthenticatedBuildMissionsIndexRouteImport } from './routes/_authenticated/build/missions.index'
import { Route as AuthenticatedBuildDossiersIndexRouteImport } from './routes/_authenticated/build/dossiers.index'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiInternalHermesProspectFunnelsRouteImport } from './routes/api/internal/hermes/prospect-funnels'
import { Route as AuthenticatedPortalDossiersIdRouteImport } from './routes/_authenticated/portal/dossiers.$id'
import { Route as AuthenticatedPortalDemosNewRouteImport } from './routes/_authenticated/portal/demos.new'
import { Route as AuthenticatedBuildRequestsIdRouteImport } from './routes/_authenticated/build/requests.$id'
import { Route as AuthenticatedBuildPlaybooksIdRouteImport } from './routes/_authenticated/build/playbooks.$id'
import { Route as AuthenticatedBuildMissionsNewRouteImport } from './routes/_authenticated/build/missions.new'
import { Route as AuthenticatedBuildMissionsIdRouteImport } from './routes/_authenticated/build/missions.$id'
import { Route as AuthenticatedBuildDossiersIdRouteImport } from './routes/_authenticated/build/dossiers.$id'
import { Route as ApiInternalHermesProspectFunnelsMetricsRouteImport } from './routes/api/internal/hermes/prospect-funnels.metrics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateBetaRoute = PrivateBetaRouteImport.update({
  id: '/private-beta',
  path: '/private-beta',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeInquiryAuditRoute = FreeInquiryAuditRouteImport.update({
  id: '/free-inquiry-audit',
  path: '/free-inquiry-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleProjectBriefRoute = ExampleProjectBriefRouteImport.update({
  id: '/example-project-brief',
  path: '/example-project-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckBuildersRoute = DeckBuildersRouteImport.update({
  id: '/deck-builders',
  path: '/deck-builders',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSummaryAccessTokenRoute =
  ProjectSummaryAccessTokenRouteImport.update({
    id: '/project-summary/$accessToken',
    path: '/project-summary/$accessToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const MPublicTokenRoute = MPublicTokenRouteImport.update({
  id: '/m/$publicToken',
  path: '/m/$publicToken',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDeckProjectRoute = DemoDeckProjectRouteImport.update({
  id: '/demo/deck-project',
  path: '/demo/deck-project',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuildRouteRoute = AuthenticatedBuildRouteRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedBuildIndexRoute = AuthenticatedBuildIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedBuildRouteRoute,
} as any)
const ApiPublicTrackViewRoute = ApiPublicTrackViewRouteImport.update({
  id: '/api/public/track-view',
  path: '/api/public/track-view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProjectSummaryRoute = ApiPublicProjectSummaryRouteImport.update({
  id: '/api/public/project-summary',
  path: '/api/public/project-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFaqAskRoute = ApiPublicFaqAskRouteImport.update({
  id: '/api/public/faq-ask',
  path: '/api/public/faq-ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildRuntimeRoute = ApiPublicBuildRuntimeRouteImport.update({
  id: '/api/public/build-runtime',
  path: '/api/public/build-runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildPublicIntakeRoute =
  ApiPublicBuildPublicIntakeRouteImport.update({
    id: '/api/public/build-public-intake',
    path: '/api/public/build-public-intake',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAnalyzeSiteRoute = ApiPublicAnalyzeSiteRouteImport.update({
  id: '/api/public/analyze-site',
  path: '/api/public/analyze-site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalTeamRoute = AuthenticatedPortalTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedPortalRouteRoute,
} as any)
const AuthenticatedPortalSetupRoute =
  AuthenticatedPortalSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalSettingsRoute =
  AuthenticatedPortalSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalMissionsRoute =
  AuthenticatedPortalMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalDemosRoute =
  AuthenticatedPortalDemosRouteImport.update({
    id: '/demos',
    path: '/demos',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalBillingRoute =
  AuthenticatedPortalBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedBuildSettingsRoute =
  AuthenticatedBuildSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildOnboardingRoute =
  AuthenticatedBuildOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildMissionsRoute =
  AuthenticatedBuildMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildKnowledgeRoute =
  AuthenticatedBuildKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildDashboardRoute =
  AuthenticatedBuildDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildActivityRoute =
  AuthenticatedBuildActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildWorkspacesIndexRoute =
  AuthenticatedBuildWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildRequestsIndexRoute =
  AuthenticatedBuildRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildPlaybooksIndexRoute =
  AuthenticatedBuildPlaybooksIndexRouteImport.update({
    id: '/playbooks/',
    path: '/playbooks/',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildMissionsIndexRoute =
  AuthenticatedBuildMissionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBuildMissionsRoute,
  } as any)
const AuthenticatedBuildDossiersIndexRoute =
  AuthenticatedBuildDossiersIndexRouteImport.update({
    id: '/dossiers/',
    path: '/dossiers/',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalHermesProspectFunnelsRoute =
  ApiInternalHermesProspectFunnelsRouteImport.update({
    id: '/api/internal/hermes/prospect-funnels',
    path: '/api/internal/hermes/prospect-funnels',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPortalDossiersIdRoute =
  AuthenticatedPortalDossiersIdRouteImport.update({
    id: '/dossiers/$id',
    path: '/dossiers/$id',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalDemosNewRoute =
  AuthenticatedPortalDemosNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPortalDemosRoute,
  } as any)
const AuthenticatedBuildRequestsIdRoute =
  AuthenticatedBuildRequestsIdRouteImport.update({
    id: '/requests/$id',
    path: '/requests/$id',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildPlaybooksIdRoute =
  AuthenticatedBuildPlaybooksIdRouteImport.update({
    id: '/playbooks/$id',
    path: '/playbooks/$id',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildMissionsNewRoute =
  AuthenticatedBuildMissionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedBuildMissionsRoute,
  } as any)
const AuthenticatedBuildMissionsIdRoute =
  AuthenticatedBuildMissionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedBuildMissionsRoute,
  } as any)
const AuthenticatedBuildDossiersIdRoute =
  AuthenticatedBuildDossiersIdRouteImport.update({
    id: '/dossiers/$id',
    path: '/dossiers/$id',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const ApiInternalHermesProspectFunnelsMetricsRoute =
  ApiInternalHermesProspectFunnelsMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => ApiInternalHermesProspectFunnelsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/deck-builders': typeof DeckBuildersRoute
  '/example-project-brief': typeof ExampleProjectBriefRoute
  '/free-inquiry-audit': typeof FreeInquiryAuditRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/private-beta': typeof PrivateBetaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/build': typeof AuthenticatedBuildRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/demo/deck-project': typeof DemoDeckProjectRoute
  '/m/$publicToken': typeof MPublicTokenRoute
  '/project-summary/$accessToken': typeof ProjectSummaryAccessTokenRoute
  '/build/activity': typeof AuthenticatedBuildActivityRoute
  '/build/dashboard': typeof AuthenticatedBuildDashboardRoute
  '/build/knowledge': typeof AuthenticatedBuildKnowledgeRoute
  '/build/missions': typeof AuthenticatedBuildMissionsRouteWithChildren
  '/build/onboarding': typeof AuthenticatedBuildOnboardingRoute
  '/build/settings': typeof AuthenticatedBuildSettingsRoute
  '/portal/billing': typeof AuthenticatedPortalBillingRoute
  '/portal/demos': typeof AuthenticatedPortalDemosRouteWithChildren
  '/portal/missions': typeof AuthenticatedPortalMissionsRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/setup': typeof AuthenticatedPortalSetupRoute
  '/portal/team': typeof AuthenticatedPortalTeamRoute
  '/api/public/analyze-site': typeof ApiPublicAnalyzeSiteRoute
  '/api/public/build-public-intake': typeof ApiPublicBuildPublicIntakeRoute
  '/api/public/build-runtime': typeof ApiPublicBuildRuntimeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/faq-ask': typeof ApiPublicFaqAskRoute
  '/api/public/project-summary': typeof ApiPublicProjectSummaryRoute
  '/api/public/track-view': typeof ApiPublicTrackViewRoute
  '/build/': typeof AuthenticatedBuildIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/build/dossiers/$id': typeof AuthenticatedBuildDossiersIdRoute
  '/build/missions/$id': typeof AuthenticatedBuildMissionsIdRoute
  '/build/missions/new': typeof AuthenticatedBuildMissionsNewRoute
  '/build/playbooks/$id': typeof AuthenticatedBuildPlaybooksIdRoute
  '/build/requests/$id': typeof AuthenticatedBuildRequestsIdRoute
  '/portal/demos/new': typeof AuthenticatedPortalDemosNewRoute
  '/portal/dossiers/$id': typeof AuthenticatedPortalDossiersIdRoute
  '/api/internal/hermes/prospect-funnels': typeof ApiInternalHermesProspectFunnelsRouteWithChildren
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/build/dossiers/': typeof AuthenticatedBuildDossiersIndexRoute
  '/build/missions/': typeof AuthenticatedBuildMissionsIndexRoute
  '/build/playbooks/': typeof AuthenticatedBuildPlaybooksIndexRoute
  '/build/requests/': typeof AuthenticatedBuildRequestsIndexRoute
  '/build/workspaces/': typeof AuthenticatedBuildWorkspacesIndexRoute
  '/api/internal/hermes/prospect-funnels/metrics': typeof ApiInternalHermesProspectFunnelsMetricsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/deck-builders': typeof DeckBuildersRoute
  '/example-project-brief': typeof ExampleProjectBriefRoute
  '/free-inquiry-audit': typeof FreeInquiryAuditRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/private-beta': typeof PrivateBetaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/demo/deck-project': typeof DemoDeckProjectRoute
  '/m/$publicToken': typeof MPublicTokenRoute
  '/project-summary/$accessToken': typeof ProjectSummaryAccessTokenRoute
  '/build/activity': typeof AuthenticatedBuildActivityRoute
  '/build/dashboard': typeof AuthenticatedBuildDashboardRoute
  '/build/knowledge': typeof AuthenticatedBuildKnowledgeRoute
  '/build/onboarding': typeof AuthenticatedBuildOnboardingRoute
  '/build/settings': typeof AuthenticatedBuildSettingsRoute
  '/portal/billing': typeof AuthenticatedPortalBillingRoute
  '/portal/demos': typeof AuthenticatedPortalDemosRouteWithChildren
  '/portal/missions': typeof AuthenticatedPortalMissionsRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/setup': typeof AuthenticatedPortalSetupRoute
  '/portal/team': typeof AuthenticatedPortalTeamRoute
  '/api/public/analyze-site': typeof ApiPublicAnalyzeSiteRoute
  '/api/public/build-public-intake': typeof ApiPublicBuildPublicIntakeRoute
  '/api/public/build-runtime': typeof ApiPublicBuildRuntimeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/faq-ask': typeof ApiPublicFaqAskRoute
  '/api/public/project-summary': typeof ApiPublicProjectSummaryRoute
  '/api/public/track-view': typeof ApiPublicTrackViewRoute
  '/build': typeof AuthenticatedBuildIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/build/dossiers/$id': typeof AuthenticatedBuildDossiersIdRoute
  '/build/missions/$id': typeof AuthenticatedBuildMissionsIdRoute
  '/build/missions/new': typeof AuthenticatedBuildMissionsNewRoute
  '/build/playbooks/$id': typeof AuthenticatedBuildPlaybooksIdRoute
  '/build/requests/$id': typeof AuthenticatedBuildRequestsIdRoute
  '/portal/demos/new': typeof AuthenticatedPortalDemosNewRoute
  '/portal/dossiers/$id': typeof AuthenticatedPortalDossiersIdRoute
  '/api/internal/hermes/prospect-funnels': typeof ApiInternalHermesProspectFunnelsRouteWithChildren
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/build/dossiers': typeof AuthenticatedBuildDossiersIndexRoute
  '/build/missions': typeof AuthenticatedBuildMissionsIndexRoute
  '/build/playbooks': typeof AuthenticatedBuildPlaybooksIndexRoute
  '/build/requests': typeof AuthenticatedBuildRequestsIndexRoute
  '/build/workspaces': typeof AuthenticatedBuildWorkspacesIndexRoute
  '/api/internal/hermes/prospect-funnels/metrics': typeof ApiInternalHermesProspectFunnelsMetricsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/deck-builders': typeof DeckBuildersRoute
  '/example-project-brief': typeof ExampleProjectBriefRoute
  '/free-inquiry-audit': typeof FreeInquiryAuditRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/private-beta': typeof PrivateBetaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/build': typeof AuthenticatedBuildRouteRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/demo/deck-project': typeof DemoDeckProjectRoute
  '/m/$publicToken': typeof MPublicTokenRoute
  '/project-summary/$accessToken': typeof ProjectSummaryAccessTokenRoute
  '/_authenticated/build/activity': typeof AuthenticatedBuildActivityRoute
  '/_authenticated/build/dashboard': typeof AuthenticatedBuildDashboardRoute
  '/_authenticated/build/knowledge': typeof AuthenticatedBuildKnowledgeRoute
  '/_authenticated/build/missions': typeof AuthenticatedBuildMissionsRouteWithChildren
  '/_authenticated/build/onboarding': typeof AuthenticatedBuildOnboardingRoute
  '/_authenticated/build/settings': typeof AuthenticatedBuildSettingsRoute
  '/_authenticated/portal/billing': typeof AuthenticatedPortalBillingRoute
  '/_authenticated/portal/demos': typeof AuthenticatedPortalDemosRouteWithChildren
  '/_authenticated/portal/missions': typeof AuthenticatedPortalMissionsRoute
  '/_authenticated/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/_authenticated/portal/setup': typeof AuthenticatedPortalSetupRoute
  '/_authenticated/portal/team': typeof AuthenticatedPortalTeamRoute
  '/api/public/analyze-site': typeof ApiPublicAnalyzeSiteRoute
  '/api/public/build-public-intake': typeof ApiPublicBuildPublicIntakeRoute
  '/api/public/build-runtime': typeof ApiPublicBuildRuntimeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/faq-ask': typeof ApiPublicFaqAskRoute
  '/api/public/project-summary': typeof ApiPublicProjectSummaryRoute
  '/api/public/track-view': typeof ApiPublicTrackViewRoute
  '/_authenticated/build/': typeof AuthenticatedBuildIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/build/dossiers/$id': typeof AuthenticatedBuildDossiersIdRoute
  '/_authenticated/build/missions/$id': typeof AuthenticatedBuildMissionsIdRoute
  '/_authenticated/build/missions/new': typeof AuthenticatedBuildMissionsNewRoute
  '/_authenticated/build/playbooks/$id': typeof AuthenticatedBuildPlaybooksIdRoute
  '/_authenticated/build/requests/$id': typeof AuthenticatedBuildRequestsIdRoute
  '/_authenticated/portal/demos/new': typeof AuthenticatedPortalDemosNewRoute
  '/_authenticated/portal/dossiers/$id': typeof AuthenticatedPortalDossiersIdRoute
  '/api/internal/hermes/prospect-funnels': typeof ApiInternalHermesProspectFunnelsRouteWithChildren
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/build/dossiers/': typeof AuthenticatedBuildDossiersIndexRoute
  '/_authenticated/build/missions/': typeof AuthenticatedBuildMissionsIndexRoute
  '/_authenticated/build/playbooks/': typeof AuthenticatedBuildPlaybooksIndexRoute
  '/_authenticated/build/requests/': typeof AuthenticatedBuildRequestsIndexRoute
  '/_authenticated/build/workspaces/': typeof AuthenticatedBuildWorkspacesIndexRoute
  '/api/internal/hermes/prospect-funnels/metrics': typeof ApiInternalHermesProspectFunnelsMetricsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/deck-builders'
    | '/example-project-brief'
    | '/free-inquiry-audit'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/private-beta'
    | '/sitemap.xml'
    | '/terms'
    | '/build'
    | '/portal'
    | '/demo/deck-project'
    | '/m/$publicToken'
    | '/project-summary/$accessToken'
    | '/build/activity'
    | '/build/dashboard'
    | '/build/knowledge'
    | '/build/missions'
    | '/build/onboarding'
    | '/build/settings'
    | '/portal/billing'
    | '/portal/demos'
    | '/portal/missions'
    | '/portal/settings'
    | '/portal/setup'
    | '/portal/team'
    | '/api/public/analyze-site'
    | '/api/public/build-public-intake'
    | '/api/public/build-runtime'
    | '/api/public/contact'
    | '/api/public/faq-ask'
    | '/api/public/project-summary'
    | '/api/public/track-view'
    | '/build/'
    | '/portal/'
    | '/build/dossiers/$id'
    | '/build/missions/$id'
    | '/build/missions/new'
    | '/build/playbooks/$id'
    | '/build/requests/$id'
    | '/portal/demos/new'
    | '/portal/dossiers/$id'
    | '/api/internal/hermes/prospect-funnels'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/build/dossiers/'
    | '/build/missions/'
    | '/build/playbooks/'
    | '/build/requests/'
    | '/build/workspaces/'
    | '/api/internal/hermes/prospect-funnels/metrics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/deck-builders'
    | '/example-project-brief'
    | '/free-inquiry-audit'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/private-beta'
    | '/sitemap.xml'
    | '/terms'
    | '/demo/deck-project'
    | '/m/$publicToken'
    | '/project-summary/$accessToken'
    | '/build/activity'
    | '/build/dashboard'
    | '/build/knowledge'
    | '/build/onboarding'
    | '/build/settings'
    | '/portal/billing'
    | '/portal/demos'
    | '/portal/missions'
    | '/portal/settings'
    | '/portal/setup'
    | '/portal/team'
    | '/api/public/analyze-site'
    | '/api/public/build-public-intake'
    | '/api/public/build-runtime'
    | '/api/public/contact'
    | '/api/public/faq-ask'
    | '/api/public/project-summary'
    | '/api/public/track-view'
    | '/build'
    | '/portal'
    | '/build/dossiers/$id'
    | '/build/missions/$id'
    | '/build/missions/new'
    | '/build/playbooks/$id'
    | '/build/requests/$id'
    | '/portal/demos/new'
    | '/portal/dossiers/$id'
    | '/api/internal/hermes/prospect-funnels'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/build/dossiers'
    | '/build/missions'
    | '/build/playbooks'
    | '/build/requests'
    | '/build/workspaces'
    | '/api/internal/hermes/prospect-funnels/metrics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/deck-builders'
    | '/example-project-brief'
    | '/free-inquiry-audit'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/private-beta'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/build'
    | '/_authenticated/portal'
    | '/demo/deck-project'
    | '/m/$publicToken'
    | '/project-summary/$accessToken'
    | '/_authenticated/build/activity'
    | '/_authenticated/build/dashboard'
    | '/_authenticated/build/knowledge'
    | '/_authenticated/build/missions'
    | '/_authenticated/build/onboarding'
    | '/_authenticated/build/settings'
    | '/_authenticated/portal/billing'
    | '/_authenticated/portal/demos'
    | '/_authenticated/portal/missions'
    | '/_authenticated/portal/settings'
    | '/_authenticated/portal/setup'
    | '/_authenticated/portal/team'
    | '/api/public/analyze-site'
    | '/api/public/build-public-intake'
    | '/api/public/build-runtime'
    | '/api/public/contact'
    | '/api/public/faq-ask'
    | '/api/public/project-summary'
    | '/api/public/track-view'
    | '/_authenticated/build/'
    | '/_authenticated/portal/'
    | '/_authenticated/build/dossiers/$id'
    | '/_authenticated/build/missions/$id'
    | '/_authenticated/build/missions/new'
    | '/_authenticated/build/playbooks/$id'
    | '/_authenticated/build/requests/$id'
    | '/_authenticated/portal/demos/new'
    | '/_authenticated/portal/dossiers/$id'
    | '/api/internal/hermes/prospect-funnels'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/build/dossiers/'
    | '/_authenticated/build/missions/'
    | '/_authenticated/build/playbooks/'
    | '/_authenticated/build/requests/'
    | '/_authenticated/build/workspaces/'
    | '/api/internal/hermes/prospect-funnels/metrics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DeckBuildersRoute: typeof DeckBuildersRoute
  ExampleProjectBriefRoute: typeof ExampleProjectBriefRoute
  FreeInquiryAuditRoute: typeof FreeInquiryAuditRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivateBetaRoute: typeof PrivateBetaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  DemoDeckProjectRoute: typeof DemoDeckProjectRoute
  MPublicTokenRoute: typeof MPublicTokenRoute
  ProjectSummaryAccessTokenRoute: typeof ProjectSummaryAccessTokenRoute
  ApiPublicAnalyzeSiteRoute: typeof ApiPublicAnalyzeSiteRoute
  ApiPublicBuildPublicIntakeRoute: typeof ApiPublicBuildPublicIntakeRoute
  ApiPublicBuildRuntimeRoute: typeof ApiPublicBuildRuntimeRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicFaqAskRoute: typeof ApiPublicFaqAskRoute
  ApiPublicProjectSummaryRoute: typeof ApiPublicProjectSummaryRoute
  ApiPublicTrackViewRoute: typeof ApiPublicTrackViewRoute
  ApiInternalHermesProspectFunnelsRoute: typeof ApiInternalHermesProspectFunnelsRouteWithChildren
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-beta': {
      id: '/private-beta'
      path: '/private-beta'
      fullPath: '/private-beta'
      preLoaderRoute: typeof PrivateBetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-inquiry-audit': {
      id: '/free-inquiry-audit'
      path: '/free-inquiry-audit'
      fullPath: '/free-inquiry-audit'
      preLoaderRoute: typeof FreeInquiryAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example-project-brief': {
      id: '/example-project-brief'
      path: '/example-project-brief'
      fullPath: '/example-project-brief'
      preLoaderRoute: typeof ExampleProjectBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck-builders': {
      id: '/deck-builders'
      path: '/deck-builders'
      fullPath: '/deck-builders'
      preLoaderRoute: typeof DeckBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-summary/$accessToken': {
      id: '/project-summary/$accessToken'
      path: '/project-summary/$accessToken'
      fullPath: '/project-summary/$accessToken'
      preLoaderRoute: typeof ProjectSummaryAccessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$publicToken': {
      id: '/m/$publicToken'
      path: '/m/$publicToken'
      fullPath: '/m/$publicToken'
      preLoaderRoute: typeof MPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/deck-project': {
      id: '/demo/deck-project'
      path: '/demo/deck-project'
      fullPath: '/demo/deck-project'
      preLoaderRoute: typeof DemoDeckProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/build': {
      id: '/_authenticated/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof AuthenticatedBuildRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/build/': {
      id: '/_authenticated/build/'
      path: '/'
      fullPath: '/build/'
      preLoaderRoute: typeof AuthenticatedBuildIndexRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/api/public/track-view': {
      id: '/api/public/track-view'
      path: '/api/public/track-view'
      fullPath: '/api/public/track-view'
      preLoaderRoute: typeof ApiPublicTrackViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/project-summary': {
      id: '/api/public/project-summary'
      path: '/api/public/project-summary'
      fullPath: '/api/public/project-summary'
      preLoaderRoute: typeof ApiPublicProjectSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/faq-ask': {
      id: '/api/public/faq-ask'
      path: '/api/public/faq-ask'
      fullPath: '/api/public/faq-ask'
      preLoaderRoute: typeof ApiPublicFaqAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/build-runtime': {
      id: '/api/public/build-runtime'
      path: '/api/public/build-runtime'
      fullPath: '/api/public/build-runtime'
      preLoaderRoute: typeof ApiPublicBuildRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/build-public-intake': {
      id: '/api/public/build-public-intake'
      path: '/api/public/build-public-intake'
      fullPath: '/api/public/build-public-intake'
      preLoaderRoute: typeof ApiPublicBuildPublicIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analyze-site': {
      id: '/api/public/analyze-site'
      path: '/api/public/analyze-site'
      fullPath: '/api/public/analyze-site'
      preLoaderRoute: typeof ApiPublicAnalyzeSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/team': {
      id: '/_authenticated/portal/team'
      path: '/team'
      fullPath: '/portal/team'
      preLoaderRoute: typeof AuthenticatedPortalTeamRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/setup': {
      id: '/_authenticated/portal/setup'
      path: '/setup'
      fullPath: '/portal/setup'
      preLoaderRoute: typeof AuthenticatedPortalSetupRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/settings': {
      id: '/_authenticated/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof AuthenticatedPortalSettingsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/missions': {
      id: '/_authenticated/portal/missions'
      path: '/missions'
      fullPath: '/portal/missions'
      preLoaderRoute: typeof AuthenticatedPortalMissionsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/demos': {
      id: '/_authenticated/portal/demos'
      path: '/demos'
      fullPath: '/portal/demos'
      preLoaderRoute: typeof AuthenticatedPortalDemosRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/billing': {
      id: '/_authenticated/portal/billing'
      path: '/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof AuthenticatedPortalBillingRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/build/settings': {
      id: '/_authenticated/build/settings'
      path: '/settings'
      fullPath: '/build/settings'
      preLoaderRoute: typeof AuthenticatedBuildSettingsRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/onboarding': {
      id: '/_authenticated/build/onboarding'
      path: '/onboarding'
      fullPath: '/build/onboarding'
      preLoaderRoute: typeof AuthenticatedBuildOnboardingRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/missions': {
      id: '/_authenticated/build/missions'
      path: '/missions'
      fullPath: '/build/missions'
      preLoaderRoute: typeof AuthenticatedBuildMissionsRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/knowledge': {
      id: '/_authenticated/build/knowledge'
      path: '/knowledge'
      fullPath: '/build/knowledge'
      preLoaderRoute: typeof AuthenticatedBuildKnowledgeRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/dashboard': {
      id: '/_authenticated/build/dashboard'
      path: '/dashboard'
      fullPath: '/build/dashboard'
      preLoaderRoute: typeof AuthenticatedBuildDashboardRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/activity': {
      id: '/_authenticated/build/activity'
      path: '/activity'
      fullPath: '/build/activity'
      preLoaderRoute: typeof AuthenticatedBuildActivityRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/workspaces/': {
      id: '/_authenticated/build/workspaces/'
      path: '/workspaces'
      fullPath: '/build/workspaces/'
      preLoaderRoute: typeof AuthenticatedBuildWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/requests/': {
      id: '/_authenticated/build/requests/'
      path: '/requests'
      fullPath: '/build/requests/'
      preLoaderRoute: typeof AuthenticatedBuildRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/playbooks/': {
      id: '/_authenticated/build/playbooks/'
      path: '/playbooks'
      fullPath: '/build/playbooks/'
      preLoaderRoute: typeof AuthenticatedBuildPlaybooksIndexRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/missions/': {
      id: '/_authenticated/build/missions/'
      path: '/'
      fullPath: '/build/missions/'
      preLoaderRoute: typeof AuthenticatedBuildMissionsIndexRouteImport
      parentRoute: typeof AuthenticatedBuildMissionsRoute
    }
    '/_authenticated/build/dossiers/': {
      id: '/_authenticated/build/dossiers/'
      path: '/dossiers'
      fullPath: '/build/dossiers/'
      preLoaderRoute: typeof AuthenticatedBuildDossiersIndexRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/hermes/prospect-funnels': {
      id: '/api/internal/hermes/prospect-funnels'
      path: '/api/internal/hermes/prospect-funnels'
      fullPath: '/api/internal/hermes/prospect-funnels'
      preLoaderRoute: typeof ApiInternalHermesProspectFunnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/dossiers/$id': {
      id: '/_authenticated/portal/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/portal/dossiers/$id'
      preLoaderRoute: typeof AuthenticatedPortalDossiersIdRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/demos/new': {
      id: '/_authenticated/portal/demos/new'
      path: '/new'
      fullPath: '/portal/demos/new'
      preLoaderRoute: typeof AuthenticatedPortalDemosNewRouteImport
      parentRoute: typeof AuthenticatedPortalDemosRoute
    }
    '/_authenticated/build/requests/$id': {
      id: '/_authenticated/build/requests/$id'
      path: '/requests/$id'
      fullPath: '/build/requests/$id'
      preLoaderRoute: typeof AuthenticatedBuildRequestsIdRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/playbooks/$id': {
      id: '/_authenticated/build/playbooks/$id'
      path: '/playbooks/$id'
      fullPath: '/build/playbooks/$id'
      preLoaderRoute: typeof AuthenticatedBuildPlaybooksIdRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/missions/new': {
      id: '/_authenticated/build/missions/new'
      path: '/new'
      fullPath: '/build/missions/new'
      preLoaderRoute: typeof AuthenticatedBuildMissionsNewRouteImport
      parentRoute: typeof AuthenticatedBuildMissionsRoute
    }
    '/_authenticated/build/missions/$id': {
      id: '/_authenticated/build/missions/$id'
      path: '/$id'
      fullPath: '/build/missions/$id'
      preLoaderRoute: typeof AuthenticatedBuildMissionsIdRouteImport
      parentRoute: typeof AuthenticatedBuildMissionsRoute
    }
    '/_authenticated/build/dossiers/$id': {
      id: '/_authenticated/build/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/build/dossiers/$id'
      preLoaderRoute: typeof AuthenticatedBuildDossiersIdRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/api/internal/hermes/prospect-funnels/metrics': {
      id: '/api/internal/hermes/prospect-funnels/metrics'
      path: '/metrics'
      fullPath: '/api/internal/hermes/prospect-funnels/metrics'
      preLoaderRoute: typeof ApiInternalHermesProspectFunnelsMetricsRouteImport
      parentRoute: typeof ApiInternalHermesProspectFunnelsRoute
    }
  }
}

interface AuthenticatedBuildMissionsRouteChildren {
  AuthenticatedBuildMissionsIdRoute: typeof AuthenticatedBuildMissionsIdRoute
  AuthenticatedBuildMissionsNewRoute: typeof AuthenticatedBuildMissionsNewRoute
  AuthenticatedBuildMissionsIndexRoute: typeof AuthenticatedBuildMissionsIndexRoute
}

const AuthenticatedBuildMissionsRouteChildren: AuthenticatedBuildMissionsRouteChildren =
  {
    AuthenticatedBuildMissionsIdRoute: AuthenticatedBuildMissionsIdRoute,
    AuthenticatedBuildMissionsNewRoute: AuthenticatedBuildMissionsNewRoute,
    AuthenticatedBuildMissionsIndexRoute: AuthenticatedBuildMissionsIndexRoute,
  }

const AuthenticatedBuildMissionsRouteWithChildren =
  AuthenticatedBuildMissionsRoute._addFileChildren(
    AuthenticatedBuildMissionsRouteChildren,
  )

interface AuthenticatedBuildRouteRouteChildren {
  AuthenticatedBuildActivityRoute: typeof AuthenticatedBuildActivityRoute
  AuthenticatedBuildDashboardRoute: typeof AuthenticatedBuildDashboardRoute
  AuthenticatedBuildKnowledgeRoute: typeof AuthenticatedBuildKnowledgeRoute
  AuthenticatedBuildMissionsRoute: typeof AuthenticatedBuildMissionsRouteWithChildren
  AuthenticatedBuildOnboardingRoute: typeof AuthenticatedBuildOnboardingRoute
  AuthenticatedBuildSettingsRoute: typeof AuthenticatedBuildSettingsRoute
  AuthenticatedBuildIndexRoute: typeof AuthenticatedBuildIndexRoute
  AuthenticatedBuildDossiersIdRoute: typeof AuthenticatedBuildDossiersIdRoute
  AuthenticatedBuildPlaybooksIdRoute: typeof AuthenticatedBuildPlaybooksIdRoute
  AuthenticatedBuildRequestsIdRoute: typeof AuthenticatedBuildRequestsIdRoute
  AuthenticatedBuildDossiersIndexRoute: typeof AuthenticatedBuildDossiersIndexRoute
  AuthenticatedBuildPlaybooksIndexRoute: typeof AuthenticatedBuildPlaybooksIndexRoute
  AuthenticatedBuildRequestsIndexRoute: typeof AuthenticatedBuildRequestsIndexRoute
  AuthenticatedBuildWorkspacesIndexRoute: typeof AuthenticatedBuildWorkspacesIndexRoute
}

const AuthenticatedBuildRouteRouteChildren: AuthenticatedBuildRouteRouteChildren =
  {
    AuthenticatedBuildActivityRoute: AuthenticatedBuildActivityRoute,
    AuthenticatedBuildDashboardRoute: AuthenticatedBuildDashboardRoute,
    AuthenticatedBuildKnowledgeRoute: AuthenticatedBuildKnowledgeRoute,
    AuthenticatedBuildMissionsRoute:
      AuthenticatedBuildMissionsRouteWithChildren,
    AuthenticatedBuildOnboardingRoute: AuthenticatedBuildOnboardingRoute,
    AuthenticatedBuildSettingsRoute: AuthenticatedBuildSettingsRoute,
    AuthenticatedBuildIndexRoute: AuthenticatedBuildIndexRoute,
    AuthenticatedBuildDossiersIdRoute: AuthenticatedBuildDossiersIdRoute,
    AuthenticatedBuildPlaybooksIdRoute: AuthenticatedBuildPlaybooksIdRoute,
    AuthenticatedBuildRequestsIdRoute: AuthenticatedBuildRequestsIdRoute,
    AuthenticatedBuildDossiersIndexRoute: AuthenticatedBuildDossiersIndexRoute,
    AuthenticatedBuildPlaybooksIndexRoute:
      AuthenticatedBuildPlaybooksIndexRoute,
    AuthenticatedBuildRequestsIndexRoute: AuthenticatedBuildRequestsIndexRoute,
    AuthenticatedBuildWorkspacesIndexRoute:
      AuthenticatedBuildWorkspacesIndexRoute,
  }

const AuthenticatedBuildRouteRouteWithChildren =
  AuthenticatedBuildRouteRoute._addFileChildren(
    AuthenticatedBuildRouteRouteChildren,
  )

interface AuthenticatedPortalDemosRouteChildren {
  AuthenticatedPortalDemosNewRoute: typeof AuthenticatedPortalDemosNewRoute
}

const AuthenticatedPortalDemosRouteChildren: AuthenticatedPortalDemosRouteChildren =
  {
    AuthenticatedPortalDemosNewRoute: AuthenticatedPortalDemosNewRoute,
  }

const AuthenticatedPortalDemosRouteWithChildren =
  AuthenticatedPortalDemosRoute._addFileChildren(
    AuthenticatedPortalDemosRouteChildren,
  )

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalBillingRoute: typeof AuthenticatedPortalBillingRoute
  AuthenticatedPortalDemosRoute: typeof AuthenticatedPortalDemosRouteWithChildren
  AuthenticatedPortalMissionsRoute: typeof AuthenticatedPortalMissionsRoute
  AuthenticatedPortalSettingsRoute: typeof AuthenticatedPortalSettingsRoute
  AuthenticatedPortalSetupRoute: typeof AuthenticatedPortalSetupRoute
  AuthenticatedPortalTeamRoute: typeof AuthenticatedPortalTeamRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalDossiersIdRoute: typeof AuthenticatedPortalDossiersIdRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalBillingRoute: AuthenticatedPortalBillingRoute,
    AuthenticatedPortalDemosRoute: AuthenticatedPortalDemosRouteWithChildren,
    AuthenticatedPortalMissionsRoute: AuthenticatedPortalMissionsRoute,
    AuthenticatedPortalSettingsRoute: AuthenticatedPortalSettingsRoute,
    AuthenticatedPortalSetupRoute: AuthenticatedPortalSetupRoute,
    AuthenticatedPortalTeamRoute: AuthenticatedPortalTeamRoute,
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
    AuthenticatedPortalDossiersIdRoute: AuthenticatedPortalDossiersIdRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuildRouteRoute: typeof AuthenticatedBuildRouteRouteWithChildren
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuildRouteRoute: AuthenticatedBuildRouteRouteWithChildren,
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiInternalHermesProspectFunnelsRouteChildren {
  ApiInternalHermesProspectFunnelsMetricsRoute: typeof ApiInternalHermesProspectFunnelsMetricsRoute
}

const ApiInternalHermesProspectFunnelsRouteChildren: ApiInternalHermesProspectFunnelsRouteChildren =
  {
    ApiInternalHermesProspectFunnelsMetricsRoute:
      ApiInternalHermesProspectFunnelsMetricsRoute,
  }

const ApiInternalHermesProspectFunnelsRouteWithChildren =
  ApiInternalHermesProspectFunnelsRoute._addFileChildren(
    ApiInternalHermesProspectFunnelsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DeckBuildersRoute: DeckBuildersRoute,
  ExampleProjectBriefRoute: ExampleProjectBriefRoute,
  FreeInquiryAuditRoute: FreeInquiryAuditRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PrivateBetaRoute: PrivateBetaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  DemoDeckProjectRoute: DemoDeckProjectRoute,
  MPublicTokenRoute: MPublicTokenRoute,
  ProjectSummaryAccessTokenRoute: ProjectSummaryAccessTokenRoute,
  ApiPublicAnalyzeSiteRoute: ApiPublicAnalyzeSiteRoute,
  ApiPublicBuildPublicIntakeRoute: ApiPublicBuildPublicIntakeRoute,
  ApiPublicBuildRuntimeRoute: ApiPublicBuildRuntimeRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicFaqAskRoute: ApiPublicFaqAskRoute,
  ApiPublicProjectSummaryRoute: ApiPublicProjectSummaryRoute,
  ApiPublicTrackViewRoute: ApiPublicTrackViewRoute,
  ApiInternalHermesProspectFunnelsRoute:
    ApiInternalHermesProspectFunnelsRouteWithChildren,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
