/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CandidatureAtelierRouteImport } from './routes/candidature-atelier'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeckBuildersRouteImport } from './routes/deck-builders'
import { Route as ExampleProjectBriefRouteImport } from './routes/example-project-brief'
import { Route as FineBinderyRouteImport } from './routes/fine-bindery'
import { Route as FreeInquiryAuditRouteImport } from './routes/free-inquiry-audit'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PartenairesRelieursRouteImport } from './routes/partenaires-relieurs'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivateBetaRouteImport } from './routes/private-beta'
import { Route as ReliureRouteImport } from './routes/reliure'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAtelierRouteRouteImport } from './routes/_authenticated/atelier/route'
import { Route as AuthenticatedBuildRouteRouteImport } from './routes/_authenticated/build/route'
import { Route as AuthenticatedMarketplaceRouteRouteImport } from './routes/_authenticated/marketplace/route'
import { Route as AuthenticatedMesLivresRouteRouteImport } from './routes/_authenticated/mes-livres/route'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as ASlugRouteImport } from './routes/a.$slug'
import { Route as DemoDeckProjectRouteImport } from './routes/demo.deck-project'
import { Route as InvitationAtelierTokenRouteImport } from './routes/invitation-atelier.$token'
import { Route as MPublicTokenRouteImport } from './routes/m.$publicToken'
import { Route as ProjectSummaryAccessTokenRouteImport } from './routes/project-summary.$accessToken'
import { Route as AuthenticatedAtelierIndexRouteImport } from './routes/_authenticated/atelier/index'
import { Route as AuthenticatedBuildIndexRouteImport } from './routes/_authenticated/build/index'
import { Route as AuthenticatedBuildActivityRouteImport } from './routes/_authenticated/build/activity'
import { Route as AuthenticatedBuildDashboardRouteImport } from './routes/_authenticated/build/dashboard'
import { Route as AuthenticatedBuildKnowledgeRouteImport } from './routes/_authenticated/build/knowledge'
import { Route as AuthenticatedBuildMissionsRouteImport } from './routes/_authenticated/build/missions'
import { Route as AuthenticatedBuildOnboardingRouteImport } from './routes/_authenticated/build/onboarding'
import { Route as AuthenticatedBuildSettingsRouteImport } from './routes/_authenticated/build/settings'
import { Route as AuthenticatedMarketplaceIndexRouteImport } from './routes/_authenticated/marketplace/index'
import { Route as AuthenticatedMarketplaceBindersRouteImport } from './routes/_authenticated/marketplace/binders'
import { Route as AuthenticatedMesLivresIndexRouteImport } from './routes/_authenticated/mes-livres/index'
import { Route as AuthenticatedMesLivresCaseIdRouteImport } from './routes/_authenticated/mes-livres/$caseId'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedPortalBillingRouteImport } from './routes/_authenticated/portal/billing'
import { Route as AuthenticatedPortalDemosRouteImport } from './routes/_authenticated/portal/demos'
import { Route as AuthenticatedPortalMissionsRouteImport } from './routes/_authenticated/portal/missions'
import { Route as AuthenticatedPortalSettingsRouteImport } from './routes/_authenticated/portal/settings'
import { Route as AuthenticatedPortalSetupRouteImport } from './routes/_authenticated/portal/setup'
import { Route as AuthenticatedPortalTeamRouteImport } from './routes/_authenticated/portal/team'
import { Route as ApiPublicAnalyzeSiteRouteImport } from './routes/api/public/analyze-site'
import { Route as ApiPublicBuildPublicIntakeRouteImport } from './routes/api/public/build-public-intake'
import { Route as ApiPublicBuildRuntimeRouteImport } from './routes/api/public/build-runtime'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicFaqAskRouteImport } from './routes/api/public/faq-ask'
import { Route as ApiPublicProjectSummaryRouteImport } from './routes/api/public/project-summary'
import { Route as ApiPublicTrackViewRouteImport } from './routes/api/public/track-view'
import { Route as AuthenticatedAtelierCasesCaseIdRouteImport } from './routes/_authenticated/atelier/cases.$caseId'
import { Route as AuthenticatedBuildDossiersIndexRouteImport } from './routes/_authenticated/build/dossiers.index'
import { Route as AuthenticatedBuildDossiersIdRouteImport } from './routes/_authenticated/build/dossiers.$id'
import { Route as AuthenticatedBuildMissionsIndexRouteImport } from './routes/_authenticated/build/missions.index'
import { Route as AuthenticatedBuildMissionsIdRouteImport } from './routes/_authenticated/build/missions.$id'
import { Route as AuthenticatedBuildMissionsNewRouteImport } from './routes/_authenticated/build/missions.new'
import { Route as AuthenticatedBuildPlaybooksIndexRouteImport } from './routes/_authenticated/build/playbooks.index'
import { Route as AuthenticatedBuildPlaybooksIdRouteImport } from './routes/_authenticated/build/playbooks.$id'
import { Route as AuthenticatedBuildRequestsIndexRouteImport } from './routes/_authenticated/build/requests.index'
import { Route as AuthenticatedBuildRequestsIdRouteImport } from './routes/_authenticated/build/requests.$id'
import { Route as AuthenticatedBuildWorkspacesIndexRouteImport } from './routes/_authenticated/build/workspaces.index'
import { Route as AuthenticatedMarketplaceCasesIndexRouteImport } from './routes/_authenticated/marketplace/cases.index'
import { Route as AuthenticatedMarketplaceCasesCaseIdRouteImport } from './routes/_authenticated/marketplace/cases.$caseId'
import { Route as AuthenticatedMarketplacePricingIndexRouteImport } from './routes/_authenticated/marketplace/pricing.index'
import { Route as AuthenticatedMarketplacePricingBinderIdRouteImport } from './routes/_authenticated/marketplace/pricing.$binderId'
import { Route as AuthenticatedPortalDemosNewRouteImport } from './routes/_authenticated/portal/demos.new'
import { Route as AuthenticatedPortalDossiersIdRouteImport } from './routes/_authenticated/portal/dossiers.$id'
import { Route as ApiInternalAnalyticsMetricsRouteImport } from './routes/api/internal/analytics/metrics'
import { Route as ApiInternalHermesProspectFunnelsRouteImport } from './routes/api/internal/hermes/prospect-funnels'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiInternalHermesProspectFunnelsMetricsRouteImport } from './routes/api/internal/hermes/prospect-funnels.metrics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatureAtelierRoute = CandidatureAtelierRouteImport.update({
  id: '/candidature-atelier',
  path: '/candidature-atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckBuildersRoute = DeckBuildersRouteImport.update({
  id: '/deck-builders',
  path: '/deck-builders',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleProjectBriefRoute = ExampleProjectBriefRouteImport.update({
  id: '/example-project-brief',
  path: '/example-project-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const FineBinderyRoute = FineBinderyRouteImport.update({
  id: '/fine-bindery',
  path: '/fine-bindery',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeInquiryAuditRoute = FreeInquiryAuditRouteImport.update({
  id: '/free-inquiry-audit',
  path: '/free-inquiry-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRelieursRoute = PartenairesRelieursRouteImport.update({
  id: '/partenaires-relieurs',
  path: '/partenaires-relieurs',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateBetaRoute = PrivateBetaRouteImport.update({
  id: '/private-beta',
  path: '/private-beta',
  getParentRoute: () => rootRouteImport,
} as any)
const ReliureRoute = ReliureRouteImport.update({
  id: '/reliure',
  path: '/reliure',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtelierRouteRoute =
  AuthenticatedAtelierRouteRouteImport.update({
    id: '/atelier',
    path: '/atelier',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuildRouteRoute = AuthenticatedBuildRouteRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRouteRoute =
  AuthenticatedMarketplaceRouteRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMesLivresRouteRoute =
  AuthenticatedMesLivresRouteRouteImport.update({
    id: '/mes-livres',
    path: '/mes-livres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ASlugRoute = ASlugRouteImport.update({
  id: '/a/$slug',
  path: '/a/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDeckProjectRoute = DemoDeckProjectRouteImport.update({
  id: '/demo/deck-project',
  path: '/demo/deck-project',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationAtelierTokenRoute = InvitationAtelierTokenRouteImport.update({
  id: '/invitation-atelier/$token',
  path: '/invitation-atelier/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MPublicTokenRoute = MPublicTokenRouteImport.update({
  id: '/m/$publicToken',
  path: '/m/$publicToken',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSummaryAccessTokenRoute =
  ProjectSummaryAccessTokenRouteImport.update({
    id: '/project-summary/$accessToken',
    path: '/project-summary/$accessToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAtelierIndexRoute =
  AuthenticatedAtelierIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAtelierRouteRoute,
  } as any)
const AuthenticatedBuildIndexRoute = AuthenticatedBuildIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedBuildRouteRoute,
} as any)
const AuthenticatedBuildActivityRoute =
  AuthenticatedBuildActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildDashboardRoute =
  AuthenticatedBuildDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildKnowledgeRoute =
  AuthenticatedBuildKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildMissionsRoute =
  AuthenticatedBuildMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildOnboardingRoute =
  AuthenticatedBuildOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildSettingsRoute =
  AuthenticatedBuildSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedMarketplaceIndexRoute =
  AuthenticatedMarketplaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMarketplaceRouteRoute,
  } as any)
const AuthenticatedMarketplaceBindersRoute =
  AuthenticatedMarketplaceBindersRouteImport.update({
    id: '/binders',
    path: '/binders',
    getParentRoute: () => AuthenticatedMarketplaceRouteRoute,
  } as any)
const AuthenticatedMesLivresIndexRoute =
  AuthenticatedMesLivresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMesLivresRouteRoute,
  } as any)
const AuthenticatedMesLivresCaseIdRoute =
  AuthenticatedMesLivresCaseIdRouteImport.update({
    id: '/$caseId',
    path: '/$caseId',
    getParentRoute: () => AuthenticatedMesLivresRouteRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalBillingRoute =
  AuthenticatedPortalBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalDemosRoute =
  AuthenticatedPortalDemosRouteImport.update({
    id: '/demos',
    path: '/demos',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalMissionsRoute =
  AuthenticatedPortalMissionsRouteImport.update({
    id: '/missions',
    path: '/missions',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalSettingsRoute =
  AuthenticatedPortalSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalSetupRoute =
  AuthenticatedPortalSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalTeamRoute = AuthenticatedPortalTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedPortalRouteRoute,
} as any)
const ApiPublicAnalyzeSiteRoute = ApiPublicAnalyzeSiteRouteImport.update({
  id: '/api/public/analyze-site',
  path: '/api/public/analyze-site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildPublicIntakeRoute =
  ApiPublicBuildPublicIntakeRouteImport.update({
    id: '/api/public/build-public-intake',
    path: '/api/public/build-public-intake',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBuildRuntimeRoute = ApiPublicBuildRuntimeRouteImport.update({
  id: '/api/public/build-runtime',
  path: '/api/public/build-runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFaqAskRoute = ApiPublicFaqAskRouteImport.update({
  id: '/api/public/faq-ask',
  path: '/api/public/faq-ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProjectSummaryRoute = ApiPublicProjectSummaryRouteImport.update({
  id: '/api/public/project-summary',
  path: '/api/public/project-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackViewRoute = ApiPublicTrackViewRouteImport.update({
  id: '/api/public/track-view',
  path: '/api/public/track-view',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtelierCasesCaseIdRoute =
  AuthenticatedAtelierCasesCaseIdRouteImport.update({
    id: '/cases/$caseId',
    path: '/cases/$caseId',
    getParentRoute: () => AuthenticatedAtelierRouteRoute,
  } as any)
const AuthenticatedBuildDossiersIndexRoute =
  AuthenticatedBuildDossiersIndexRouteImport.update({
    id: '/dossiers/',
    path: '/dossiers/',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildDossiersIdRoute =
  AuthenticatedBuildDossiersIdRouteImport.update({
    id: '/dossiers/$id',
    path: '/dossiers/$id',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildMissionsIndexRoute =
  AuthenticatedBuildMissionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBuildMissionsRoute,
  } as any)
const AuthenticatedBuildMissionsIdRoute =
  AuthenticatedBuildMissionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedBuildMissionsRoute,
  } as any)
const AuthenticatedBuildMissionsNewRoute =
  AuthenticatedBuildMissionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedBuildMissionsRoute,
  } as any)
const AuthenticatedBuildPlaybooksIndexRoute =
  AuthenticatedBuildPlaybooksIndexRouteImport.update({
    id: '/playbooks/',
    path: '/playbooks/',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildPlaybooksIdRoute =
  AuthenticatedBuildPlaybooksIdRouteImport.update({
    id: '/playbooks/$id',
    path: '/playbooks/$id',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildRequestsIndexRoute =
  AuthenticatedBuildRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildRequestsIdRoute =
  AuthenticatedBuildRequestsIdRouteImport.update({
    id: '/requests/$id',
    path: '/requests/$id',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedBuildWorkspacesIndexRoute =
  AuthenticatedBuildWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedBuildRouteRoute,
  } as any)
const AuthenticatedMarketplaceCasesIndexRoute =
  AuthenticatedMarketplaceCasesIndexRouteImport.update({
    id: '/cases/',
    path: '/cases/',
    getParentRoute: () => AuthenticatedMarketplaceRouteRoute,
  } as any)
const AuthenticatedMarketplaceCasesCaseIdRoute =
  AuthenticatedMarketplaceCasesCaseIdRouteImport.update({
    id: '/cases/$caseId',
    path: '/cases/$caseId',
    getParentRoute: () => AuthenticatedMarketplaceRouteRoute,
  } as any)
const AuthenticatedMarketplacePricingIndexRoute =
  AuthenticatedMarketplacePricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => AuthenticatedMarketplaceRouteRoute,
  } as any)
const AuthenticatedMarketplacePricingBinderIdRoute =
  AuthenticatedMarketplacePricingBinderIdRouteImport.update({
    id: '/pricing/$binderId',
    path: '/pricing/$binderId',
    getParentRoute: () => AuthenticatedMarketplaceRouteRoute,
  } as any)
const AuthenticatedPortalDemosNewRoute =
  AuthenticatedPortalDemosNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPortalDemosRoute,
  } as any)
const AuthenticatedPortalDossiersIdRoute =
  AuthenticatedPortalDossiersIdRouteImport.update({
    id: '/dossiers/$id',
    path: '/dossiers/$id',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const ApiInternalAnalyticsMetricsRoute =
  ApiInternalAnalyticsMetricsRouteImport.update({
    id: '/api/internal/analytics/metrics',
    path: '/api/internal/analytics/metrics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalHermesProspectFunnelsRoute =
  ApiInternalHermesProspectFunnelsRouteImport.update({
    id: '/api/internal/hermes/prospect-funnels',
    path: '/api/internal/hermes/prospect-funnels',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalHermesProspectFunnelsMetricsRoute =
  ApiInternalHermesProspectFunnelsMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => ApiInternalHermesProspectFunnelsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidature-atelier': typeof CandidatureAtelierRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/deck-builders': typeof DeckBuildersRoute
  '/example-project-brief': typeof ExampleProjectBriefRoute
  '/fine-bindery': typeof FineBinderyRoute
  '/free-inquiry-audit': typeof FreeInquiryAuditRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires-relieurs': typeof PartenairesRelieursRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/private-beta': typeof PrivateBetaRoute
  '/reliure': typeof ReliureRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/terms': typeof TermsRoute
  '/atelier': typeof AuthenticatedAtelierRouteRouteWithChildren
  '/build': typeof AuthenticatedBuildRouteRouteWithChildren
  '/marketplace': typeof AuthenticatedMarketplaceRouteRouteWithChildren
  '/mes-livres': typeof AuthenticatedMesLivresRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/a/$slug': typeof ASlugRoute
  '/demo/deck-project': typeof DemoDeckProjectRoute
  '/invitation-atelier/$token': typeof InvitationAtelierTokenRoute
  '/m/$publicToken': typeof MPublicTokenRoute
  '/project-summary/$accessToken': typeof ProjectSummaryAccessTokenRoute
  '/build/activity': typeof AuthenticatedBuildActivityRoute
  '/build/dashboard': typeof AuthenticatedBuildDashboardRoute
  '/build/knowledge': typeof AuthenticatedBuildKnowledgeRoute
  '/build/missions': typeof AuthenticatedBuildMissionsRouteWithChildren
  '/build/onboarding': typeof AuthenticatedBuildOnboardingRoute
  '/build/settings': typeof AuthenticatedBuildSettingsRoute
  '/marketplace/binders': typeof AuthenticatedMarketplaceBindersRoute
  '/mes-livres/$caseId': typeof AuthenticatedMesLivresCaseIdRoute
  '/portal/billing': typeof AuthenticatedPortalBillingRoute
  '/portal/demos': typeof AuthenticatedPortalDemosRouteWithChildren
  '/portal/missions': typeof AuthenticatedPortalMissionsRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/setup': typeof AuthenticatedPortalSetupRoute
  '/portal/team': typeof AuthenticatedPortalTeamRoute
  '/api/public/analyze-site': typeof ApiPublicAnalyzeSiteRoute
  '/api/public/build-public-intake': typeof ApiPublicBuildPublicIntakeRoute
  '/api/public/build-runtime': typeof ApiPublicBuildRuntimeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/faq-ask': typeof ApiPublicFaqAskRoute
  '/api/public/project-summary': typeof ApiPublicProjectSummaryRoute
  '/api/public/track-view': typeof ApiPublicTrackViewRoute
  '/atelier/': typeof AuthenticatedAtelierIndexRoute
  '/build/': typeof AuthenticatedBuildIndexRoute
  '/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/mes-livres/': typeof AuthenticatedMesLivresIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/atelier/cases/$caseId': typeof AuthenticatedAtelierCasesCaseIdRoute
  '/build/dossiers/$id': typeof AuthenticatedBuildDossiersIdRoute
  '/build/missions/$id': typeof AuthenticatedBuildMissionsIdRoute
  '/build/missions/new': typeof AuthenticatedBuildMissionsNewRoute
  '/build/playbooks/$id': typeof AuthenticatedBuildPlaybooksIdRoute
  '/build/requests/$id': typeof AuthenticatedBuildRequestsIdRoute
  '/marketplace/cases/$caseId': typeof AuthenticatedMarketplaceCasesCaseIdRoute
  '/marketplace/pricing/$binderId': typeof AuthenticatedMarketplacePricingBinderIdRoute
  '/portal/demos/new': typeof AuthenticatedPortalDemosNewRoute
  '/portal/dossiers/$id': typeof AuthenticatedPortalDossiersIdRoute
  '/api/internal/analytics/metrics': typeof ApiInternalAnalyticsMetricsRoute
  '/api/internal/hermes/prospect-funnels': typeof ApiInternalHermesProspectFunnelsRouteWithChildren
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/build/dossiers/': typeof AuthenticatedBuildDossiersIndexRoute
  '/build/missions/': typeof AuthenticatedBuildMissionsIndexRoute
  '/build/playbooks/': typeof AuthenticatedBuildPlaybooksIndexRoute
  '/build/requests/': typeof AuthenticatedBuildRequestsIndexRoute
  '/build/workspaces/': typeof AuthenticatedBuildWorkspacesIndexRoute
  '/marketplace/cases/': typeof AuthenticatedMarketplaceCasesIndexRoute
  '/marketplace/pricing/': typeof AuthenticatedMarketplacePricingIndexRoute
  '/api/internal/hermes/prospect-funnels/metrics': typeof ApiInternalHermesProspectFunnelsMetricsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidature-atelier': typeof CandidatureAtelierRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/deck-builders': typeof DeckBuildersRoute
  '/example-project-brief': typeof ExampleProjectBriefRoute
  '/fine-bindery': typeof FineBinderyRoute
  '/free-inquiry-audit': typeof FreeInquiryAuditRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires-relieurs': typeof PartenairesRelieursRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/private-beta': typeof PrivateBetaRoute
  '/reliure': typeof ReliureRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/terms': typeof TermsRoute
  '/a/$slug': typeof ASlugRoute
  '/demo/deck-project': typeof DemoDeckProjectRoute
  '/invitation-atelier/$token': typeof InvitationAtelierTokenRoute
  '/m/$publicToken': typeof MPublicTokenRoute
  '/project-summary/$accessToken': typeof ProjectSummaryAccessTokenRoute
  '/build/activity': typeof AuthenticatedBuildActivityRoute
  '/build/dashboard': typeof AuthenticatedBuildDashboardRoute
  '/build/knowledge': typeof AuthenticatedBuildKnowledgeRoute
  '/build/onboarding': typeof AuthenticatedBuildOnboardingRoute
  '/build/settings': typeof AuthenticatedBuildSettingsRoute
  '/marketplace/binders': typeof AuthenticatedMarketplaceBindersRoute
  '/mes-livres/$caseId': typeof AuthenticatedMesLivresCaseIdRoute
  '/portal/billing': typeof AuthenticatedPortalBillingRoute
  '/portal/demos': typeof AuthenticatedPortalDemosRouteWithChildren
  '/portal/missions': typeof AuthenticatedPortalMissionsRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/setup': typeof AuthenticatedPortalSetupRoute
  '/portal/team': typeof AuthenticatedPortalTeamRoute
  '/api/public/analyze-site': typeof ApiPublicAnalyzeSiteRoute
  '/api/public/build-public-intake': typeof ApiPublicBuildPublicIntakeRoute
  '/api/public/build-runtime': typeof ApiPublicBuildRuntimeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/faq-ask': typeof ApiPublicFaqAskRoute
  '/api/public/project-summary': typeof ApiPublicProjectSummaryRoute
  '/api/public/track-view': typeof ApiPublicTrackViewRoute
  '/atelier': typeof AuthenticatedAtelierIndexRoute
  '/build': typeof AuthenticatedBuildIndexRoute
  '/marketplace': typeof AuthenticatedMarketplaceIndexRoute
  '/mes-livres': typeof AuthenticatedMesLivresIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/atelier/cases/$caseId': typeof AuthenticatedAtelierCasesCaseIdRoute
  '/build/dossiers/$id': typeof AuthenticatedBuildDossiersIdRoute
  '/build/missions/$id': typeof AuthenticatedBuildMissionsIdRoute
  '/build/missions/new': typeof AuthenticatedBuildMissionsNewRoute
  '/build/playbooks/$id': typeof AuthenticatedBuildPlaybooksIdRoute
  '/build/requests/$id': typeof AuthenticatedBuildRequestsIdRoute
  '/marketplace/cases/$caseId': typeof AuthenticatedMarketplaceCasesCaseIdRoute
  '/marketplace/pricing/$binderId': typeof AuthenticatedMarketplacePricingBinderIdRoute
  '/portal/demos/new': typeof AuthenticatedPortalDemosNewRoute
  '/portal/dossiers/$id': typeof AuthenticatedPortalDossiersIdRoute
  '/api/internal/analytics/metrics': typeof ApiInternalAnalyticsMetricsRoute
  '/api/internal/hermes/prospect-funnels': typeof ApiInternalHermesProspectFunnelsRouteWithChildren
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/build/dossiers': typeof AuthenticatedBuildDossiersIndexRoute
  '/build/missions': typeof AuthenticatedBuildMissionsIndexRoute
  '/build/playbooks': typeof AuthenticatedBuildPlaybooksIndexRoute
  '/build/requests': typeof AuthenticatedBuildRequestsIndexRoute
  '/build/workspaces': typeof AuthenticatedBuildWorkspacesIndexRoute
  '/marketplace/cases': typeof AuthenticatedMarketplaceCasesIndexRoute
  '/marketplace/pricing': typeof AuthenticatedMarketplacePricingIndexRoute
  '/api/internal/hermes/prospect-funnels/metrics': typeof ApiInternalHermesProspectFunnelsMetricsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/candidature-atelier': typeof CandidatureAtelierRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/deck-builders': typeof DeckBuildersRoute
  '/example-project-brief': typeof ExampleProjectBriefRoute
  '/fine-bindery': typeof FineBinderyRoute
  '/free-inquiry-audit': typeof FreeInquiryAuditRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires-relieurs': typeof PartenairesRelieursRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/private-beta': typeof PrivateBetaRoute
  '/reliure': typeof ReliureRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/terms': typeof TermsRoute
  '/_authenticated/atelier': typeof AuthenticatedAtelierRouteRouteWithChildren
  '/_authenticated/build': typeof AuthenticatedBuildRouteRouteWithChildren
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRouteRouteWithChildren
  '/_authenticated/mes-livres': typeof AuthenticatedMesLivresRouteRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/a/$slug': typeof ASlugRoute
  '/demo/deck-project': typeof DemoDeckProjectRoute
  '/invitation-atelier/$token': typeof InvitationAtelierTokenRoute
  '/m/$publicToken': typeof MPublicTokenRoute
  '/project-summary/$accessToken': typeof ProjectSummaryAccessTokenRoute
  '/_authenticated/build/activity': typeof AuthenticatedBuildActivityRoute
  '/_authenticated/build/dashboard': typeof AuthenticatedBuildDashboardRoute
  '/_authenticated/build/knowledge': typeof AuthenticatedBuildKnowledgeRoute
  '/_authenticated/build/missions': typeof AuthenticatedBuildMissionsRouteWithChildren
  '/_authenticated/build/onboarding': typeof AuthenticatedBuildOnboardingRoute
  '/_authenticated/build/settings': typeof AuthenticatedBuildSettingsRoute
  '/_authenticated/marketplace/binders': typeof AuthenticatedMarketplaceBindersRoute
  '/_authenticated/mes-livres/$caseId': typeof AuthenticatedMesLivresCaseIdRoute
  '/_authenticated/portal/billing': typeof AuthenticatedPortalBillingRoute
  '/_authenticated/portal/demos': typeof AuthenticatedPortalDemosRouteWithChildren
  '/_authenticated/portal/missions': typeof AuthenticatedPortalMissionsRoute
  '/_authenticated/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/_authenticated/portal/setup': typeof AuthenticatedPortalSetupRoute
  '/_authenticated/portal/team': typeof AuthenticatedPortalTeamRoute
  '/api/public/analyze-site': typeof ApiPublicAnalyzeSiteRoute
  '/api/public/build-public-intake': typeof ApiPublicBuildPublicIntakeRoute
  '/api/public/build-runtime': typeof ApiPublicBuildRuntimeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/faq-ask': typeof ApiPublicFaqAskRoute
  '/api/public/project-summary': typeof ApiPublicProjectSummaryRoute
  '/api/public/track-view': typeof ApiPublicTrackViewRoute
  '/_authenticated/atelier/': typeof AuthenticatedAtelierIndexRoute
  '/_authenticated/build/': typeof AuthenticatedBuildIndexRoute
  '/_authenticated/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/_authenticated/mes-livres/': typeof AuthenticatedMesLivresIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/atelier/cases/$caseId': typeof AuthenticatedAtelierCasesCaseIdRoute
  '/_authenticated/build/dossiers/$id': typeof AuthenticatedBuildDossiersIdRoute
  '/_authenticated/build/missions/$id': typeof AuthenticatedBuildMissionsIdRoute
  '/_authenticated/build/missions/new': typeof AuthenticatedBuildMissionsNewRoute
  '/_authenticated/build/playbooks/$id': typeof AuthenticatedBuildPlaybooksIdRoute
  '/_authenticated/build/requests/$id': typeof AuthenticatedBuildRequestsIdRoute
  '/_authenticated/marketplace/cases/$caseId': typeof AuthenticatedMarketplaceCasesCaseIdRoute
  '/_authenticated/marketplace/pricing/$binderId': typeof AuthenticatedMarketplacePricingBinderIdRoute
  '/_authenticated/portal/demos/new': typeof AuthenticatedPortalDemosNewRoute
  '/_authenticated/portal/dossiers/$id': typeof AuthenticatedPortalDossiersIdRoute
  '/api/internal/analytics/metrics': typeof ApiInternalAnalyticsMetricsRoute
  '/api/internal/hermes/prospect-funnels': typeof ApiInternalHermesProspectFunnelsRouteWithChildren
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/build/dossiers/': typeof AuthenticatedBuildDossiersIndexRoute
  '/_authenticated/build/missions/': typeof AuthenticatedBuildMissionsIndexRoute
  '/_authenticated/build/playbooks/': typeof AuthenticatedBuildPlaybooksIndexRoute
  '/_authenticated/build/requests/': typeof AuthenticatedBuildRequestsIndexRoute
  '/_authenticated/build/workspaces/': typeof AuthenticatedBuildWorkspacesIndexRoute
  '/_authenticated/marketplace/cases/': typeof AuthenticatedMarketplaceCasesIndexRoute
  '/_authenticated/marketplace/pricing/': typeof AuthenticatedMarketplacePricingIndexRoute
  '/api/internal/hermes/prospect-funnels/metrics': typeof ApiInternalHermesProspectFunnelsMetricsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/candidature-atelier'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/deck-builders'
    | '/example-project-brief'
    | '/fine-bindery'
    | '/free-inquiry-audit'
    | '/how-it-works'
    | '/mentions-legales'
    | '/partenaires-relieurs'
    | '/pricing'
    | '/privacy'
    | '/private-beta'
    | '/reliure'
    | '/sitemap.xml'
    | '/tarifs'
    | '/terms'
    | '/atelier'
    | '/build'
    | '/marketplace'
    | '/mes-livres'
    | '/portal'
    | '/a/$slug'
    | '/demo/deck-project'
    | '/invitation-atelier/$token'
    | '/m/$publicToken'
    | '/project-summary/$accessToken'
    | '/build/activity'
    | '/build/dashboard'
    | '/build/knowledge'
    | '/build/missions'
    | '/build/onboarding'
    | '/build/settings'
    | '/marketplace/binders'
    | '/mes-livres/$caseId'
    | '/portal/billing'
    | '/portal/demos'
    | '/portal/missions'
    | '/portal/settings'
    | '/portal/setup'
    | '/portal/team'
    | '/api/public/analyze-site'
    | '/api/public/build-public-intake'
    | '/api/public/build-runtime'
    | '/api/public/contact'
    | '/api/public/faq-ask'
    | '/api/public/project-summary'
    | '/api/public/track-view'
    | '/atelier/'
    | '/build/'
    | '/marketplace/'
    | '/mes-livres/'
    | '/portal/'
    | '/atelier/cases/$caseId'
    | '/build/dossiers/$id'
    | '/build/missions/$id'
    | '/build/missions/new'
    | '/build/playbooks/$id'
    | '/build/requests/$id'
    | '/marketplace/cases/$caseId'
    | '/marketplace/pricing/$binderId'
    | '/portal/demos/new'
    | '/portal/dossiers/$id'
    | '/api/internal/analytics/metrics'
    | '/api/internal/hermes/prospect-funnels'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/build/dossiers/'
    | '/build/missions/'
    | '/build/playbooks/'
    | '/build/requests/'
    | '/build/workspaces/'
    | '/marketplace/cases/'
    | '/marketplace/pricing/'
    | '/api/internal/hermes/prospect-funnels/metrics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/candidature-atelier'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/deck-builders'
    | '/example-project-brief'
    | '/fine-bindery'
    | '/free-inquiry-audit'
    | '/how-it-works'
    | '/mentions-legales'
    | '/partenaires-relieurs'
    | '/pricing'
    | '/privacy'
    | '/private-beta'
    | '/reliure'
    | '/sitemap.xml'
    | '/tarifs'
    | '/terms'
    | '/a/$slug'
    | '/demo/deck-project'
    | '/invitation-atelier/$token'
    | '/m/$publicToken'
    | '/project-summary/$accessToken'
    | '/build/activity'
    | '/build/dashboard'
    | '/build/knowledge'
    | '/build/onboarding'
    | '/build/settings'
    | '/marketplace/binders'
    | '/mes-livres/$caseId'
    | '/portal/billing'
    | '/portal/demos'
    | '/portal/missions'
    | '/portal/settings'
    | '/portal/setup'
    | '/portal/team'
    | '/api/public/analyze-site'
    | '/api/public/build-public-intake'
    | '/api/public/build-runtime'
    | '/api/public/contact'
    | '/api/public/faq-ask'
    | '/api/public/project-summary'
    | '/api/public/track-view'
    | '/atelier'
    | '/build'
    | '/marketplace'
    | '/mes-livres'
    | '/portal'
    | '/atelier/cases/$caseId'
    | '/build/dossiers/$id'
    | '/build/missions/$id'
    | '/build/missions/new'
    | '/build/playbooks/$id'
    | '/build/requests/$id'
    | '/marketplace/cases/$caseId'
    | '/marketplace/pricing/$binderId'
    | '/portal/demos/new'
    | '/portal/dossiers/$id'
    | '/api/internal/analytics/metrics'
    | '/api/internal/hermes/prospect-funnels'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/build/dossiers'
    | '/build/missions'
    | '/build/playbooks'
    | '/build/requests'
    | '/build/workspaces'
    | '/marketplace/cases'
    | '/marketplace/pricing'
    | '/api/internal/hermes/prospect-funnels/metrics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/candidature-atelier'
    | '/conditions'
    | '/confidentialite'
    | '/contact'
    | '/deck-builders'
    | '/example-project-brief'
    | '/fine-bindery'
    | '/free-inquiry-audit'
    | '/how-it-works'
    | '/mentions-legales'
    | '/partenaires-relieurs'
    | '/pricing'
    | '/privacy'
    | '/private-beta'
    | '/reliure'
    | '/sitemap.xml'
    | '/tarifs'
    | '/terms'
    | '/_authenticated/atelier'
    | '/_authenticated/build'
    | '/_authenticated/marketplace'
    | '/_authenticated/mes-livres'
    | '/_authenticated/portal'
    | '/a/$slug'
    | '/demo/deck-project'
    | '/invitation-atelier/$token'
    | '/m/$publicToken'
    | '/project-summary/$accessToken'
    | '/_authenticated/build/activity'
    | '/_authenticated/build/dashboard'
    | '/_authenticated/build/knowledge'
    | '/_authenticated/build/missions'
    | '/_authenticated/build/onboarding'
    | '/_authenticated/build/settings'
    | '/_authenticated/marketplace/binders'
    | '/_authenticated/mes-livres/$caseId'
    | '/_authenticated/portal/billing'
    | '/_authenticated/portal/demos'
    | '/_authenticated/portal/missions'
    | '/_authenticated/portal/settings'
    | '/_authenticated/portal/setup'
    | '/_authenticated/portal/team'
    | '/api/public/analyze-site'
    | '/api/public/build-public-intake'
    | '/api/public/build-runtime'
    | '/api/public/contact'
    | '/api/public/faq-ask'
    | '/api/public/project-summary'
    | '/api/public/track-view'
    | '/_authenticated/atelier/'
    | '/_authenticated/build/'
    | '/_authenticated/marketplace/'
    | '/_authenticated/mes-livres/'
    | '/_authenticated/portal/'
    | '/_authenticated/atelier/cases/$caseId'
    | '/_authenticated/build/dossiers/$id'
    | '/_authenticated/build/missions/$id'
    | '/_authenticated/build/missions/new'
    | '/_authenticated/build/playbooks/$id'
    | '/_authenticated/build/requests/$id'
    | '/_authenticated/marketplace/cases/$caseId'
    | '/_authenticated/marketplace/pricing/$binderId'
    | '/_authenticated/portal/demos/new'
    | '/_authenticated/portal/dossiers/$id'
    | '/api/internal/analytics/metrics'
    | '/api/internal/hermes/prospect-funnels'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/build/dossiers/'
    | '/_authenticated/build/missions/'
    | '/_authenticated/build/playbooks/'
    | '/_authenticated/build/requests/'
    | '/_authenticated/build/workspaces/'
    | '/_authenticated/marketplace/cases/'
    | '/_authenticated/marketplace/pricing/'
    | '/api/internal/hermes/prospect-funnels/metrics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CandidatureAtelierRoute: typeof CandidatureAtelierRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  DeckBuildersRoute: typeof DeckBuildersRoute
  ExampleProjectBriefRoute: typeof ExampleProjectBriefRoute
  FineBinderyRoute: typeof FineBinderyRoute
  FreeInquiryAuditRoute: typeof FreeInquiryAuditRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PartenairesRelieursRoute: typeof PartenairesRelieursRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivateBetaRoute: typeof PrivateBetaRoute
  ReliureRoute: typeof ReliureRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
  TermsRoute: typeof TermsRoute
  ASlugRoute: typeof ASlugRoute
  DemoDeckProjectRoute: typeof DemoDeckProjectRoute
  InvitationAtelierTokenRoute: typeof InvitationAtelierTokenRoute
  MPublicTokenRoute: typeof MPublicTokenRoute
  ProjectSummaryAccessTokenRoute: typeof ProjectSummaryAccessTokenRoute
  ApiPublicAnalyzeSiteRoute: typeof ApiPublicAnalyzeSiteRoute
  ApiPublicBuildPublicIntakeRoute: typeof ApiPublicBuildPublicIntakeRoute
  ApiPublicBuildRuntimeRoute: typeof ApiPublicBuildRuntimeRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicFaqAskRoute: typeof ApiPublicFaqAskRoute
  ApiPublicProjectSummaryRoute: typeof ApiPublicProjectSummaryRoute
  ApiPublicTrackViewRoute: typeof ApiPublicTrackViewRoute
  ApiInternalAnalyticsMetricsRoute: typeof ApiInternalAnalyticsMetricsRoute
  ApiInternalHermesProspectFunnelsRoute: typeof ApiInternalHermesProspectFunnelsRouteWithChildren
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidature-atelier': {
      id: '/candidature-atelier'
      path: '/candidature-atelier'
      fullPath: '/candidature-atelier'
      preLoaderRoute: typeof CandidatureAtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck-builders': {
      id: '/deck-builders'
      path: '/deck-builders'
      fullPath: '/deck-builders'
      preLoaderRoute: typeof DeckBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example-project-brief': {
      id: '/example-project-brief'
      path: '/example-project-brief'
      fullPath: '/example-project-brief'
      preLoaderRoute: typeof ExampleProjectBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fine-bindery': {
      id: '/fine-bindery'
      path: '/fine-bindery'
      fullPath: '/fine-bindery'
      preLoaderRoute: typeof FineBinderyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-inquiry-audit': {
      id: '/free-inquiry-audit'
      path: '/free-inquiry-audit'
      fullPath: '/free-inquiry-audit'
      preLoaderRoute: typeof FreeInquiryAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires-relieurs': {
      id: '/partenaires-relieurs'
      path: '/partenaires-relieurs'
      fullPath: '/partenaires-relieurs'
      preLoaderRoute: typeof PartenairesRelieursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-beta': {
      id: '/private-beta'
      path: '/private-beta'
      fullPath: '/private-beta'
      preLoaderRoute: typeof PrivateBetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reliure': {
      id: '/reliure'
      path: '/reliure'
      fullPath: '/reliure'
      preLoaderRoute: typeof ReliureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atelier': {
      id: '/_authenticated/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AuthenticatedAtelierRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/build': {
      id: '/_authenticated/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof AuthenticatedBuildRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-livres': {
      id: '/_authenticated/mes-livres'
      path: '/mes-livres'
      fullPath: '/mes-livres'
      preLoaderRoute: typeof AuthenticatedMesLivresRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/a/$slug': {
      id: '/a/$slug'
      path: '/a/$slug'
      fullPath: '/a/$slug'
      preLoaderRoute: typeof ASlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/deck-project': {
      id: '/demo/deck-project'
      path: '/demo/deck-project'
      fullPath: '/demo/deck-project'
      preLoaderRoute: typeof DemoDeckProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation-atelier/$token': {
      id: '/invitation-atelier/$token'
      path: '/invitation-atelier/$token'
      fullPath: '/invitation-atelier/$token'
      preLoaderRoute: typeof InvitationAtelierTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$publicToken': {
      id: '/m/$publicToken'
      path: '/m/$publicToken'
      fullPath: '/m/$publicToken'
      preLoaderRoute: typeof MPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-summary/$accessToken': {
      id: '/project-summary/$accessToken'
      path: '/project-summary/$accessToken'
      fullPath: '/project-summary/$accessToken'
      preLoaderRoute: typeof ProjectSummaryAccessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atelier/': {
      id: '/_authenticated/atelier/'
      path: '/'
      fullPath: '/atelier/'
      preLoaderRoute: typeof AuthenticatedAtelierIndexRouteImport
      parentRoute: typeof AuthenticatedAtelierRouteRoute
    }
    '/_authenticated/build/': {
      id: '/_authenticated/build/'
      path: '/'
      fullPath: '/build/'
      preLoaderRoute: typeof AuthenticatedBuildIndexRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/activity': {
      id: '/_authenticated/build/activity'
      path: '/activity'
      fullPath: '/build/activity'
      preLoaderRoute: typeof AuthenticatedBuildActivityRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/dashboard': {
      id: '/_authenticated/build/dashboard'
      path: '/dashboard'
      fullPath: '/build/dashboard'
      preLoaderRoute: typeof AuthenticatedBuildDashboardRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/knowledge': {
      id: '/_authenticated/build/knowledge'
      path: '/knowledge'
      fullPath: '/build/knowledge'
      preLoaderRoute: typeof AuthenticatedBuildKnowledgeRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/missions': {
      id: '/_authenticated/build/missions'
      path: '/missions'
      fullPath: '/build/missions'
      preLoaderRoute: typeof AuthenticatedBuildMissionsRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/onboarding': {
      id: '/_authenticated/build/onboarding'
      path: '/onboarding'
      fullPath: '/build/onboarding'
      preLoaderRoute: typeof AuthenticatedBuildOnboardingRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/settings': {
      id: '/_authenticated/build/settings'
      path: '/settings'
      fullPath: '/build/settings'
      preLoaderRoute: typeof AuthenticatedBuildSettingsRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/marketplace/': {
      id: '/_authenticated/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AuthenticatedMarketplaceIndexRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRouteRoute
    }
    '/_authenticated/marketplace/binders': {
      id: '/_authenticated/marketplace/binders'
      path: '/binders'
      fullPath: '/marketplace/binders'
      preLoaderRoute: typeof AuthenticatedMarketplaceBindersRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRouteRoute
    }
    '/_authenticated/mes-livres/': {
      id: '/_authenticated/mes-livres/'
      path: '/'
      fullPath: '/mes-livres/'
      preLoaderRoute: typeof AuthenticatedMesLivresIndexRouteImport
      parentRoute: typeof AuthenticatedMesLivresRouteRoute
    }
    '/_authenticated/mes-livres/$caseId': {
      id: '/_authenticated/mes-livres/$caseId'
      path: '/$caseId'
      fullPath: '/mes-livres/$caseId'
      preLoaderRoute: typeof AuthenticatedMesLivresCaseIdRouteImport
      parentRoute: typeof AuthenticatedMesLivresRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/billing': {
      id: '/_authenticated/portal/billing'
      path: '/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof AuthenticatedPortalBillingRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/demos': {
      id: '/_authenticated/portal/demos'
      path: '/demos'
      fullPath: '/portal/demos'
      preLoaderRoute: typeof AuthenticatedPortalDemosRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/missions': {
      id: '/_authenticated/portal/missions'
      path: '/missions'
      fullPath: '/portal/missions'
      preLoaderRoute: typeof AuthenticatedPortalMissionsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/settings': {
      id: '/_authenticated/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof AuthenticatedPortalSettingsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/setup': {
      id: '/_authenticated/portal/setup'
      path: '/setup'
      fullPath: '/portal/setup'
      preLoaderRoute: typeof AuthenticatedPortalSetupRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/team': {
      id: '/_authenticated/portal/team'
      path: '/team'
      fullPath: '/portal/team'
      preLoaderRoute: typeof AuthenticatedPortalTeamRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/api/public/analyze-site': {
      id: '/api/public/analyze-site'
      path: '/api/public/analyze-site'
      fullPath: '/api/public/analyze-site'
      preLoaderRoute: typeof ApiPublicAnalyzeSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/build-public-intake': {
      id: '/api/public/build-public-intake'
      path: '/api/public/build-public-intake'
      fullPath: '/api/public/build-public-intake'
      preLoaderRoute: typeof ApiPublicBuildPublicIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/build-runtime': {
      id: '/api/public/build-runtime'
      path: '/api/public/build-runtime'
      fullPath: '/api/public/build-runtime'
      preLoaderRoute: typeof ApiPublicBuildRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/faq-ask': {
      id: '/api/public/faq-ask'
      path: '/api/public/faq-ask'
      fullPath: '/api/public/faq-ask'
      preLoaderRoute: typeof ApiPublicFaqAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/project-summary': {
      id: '/api/public/project-summary'
      path: '/api/public/project-summary'
      fullPath: '/api/public/project-summary'
      preLoaderRoute: typeof ApiPublicProjectSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-view': {
      id: '/api/public/track-view'
      path: '/api/public/track-view'
      fullPath: '/api/public/track-view'
      preLoaderRoute: typeof ApiPublicTrackViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atelier/cases/$caseId': {
      id: '/_authenticated/atelier/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/atelier/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedAtelierCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedAtelierRouteRoute
    }
    '/_authenticated/build/dossiers/': {
      id: '/_authenticated/build/dossiers/'
      path: '/dossiers'
      fullPath: '/build/dossiers/'
      preLoaderRoute: typeof AuthenticatedBuildDossiersIndexRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/dossiers/$id': {
      id: '/_authenticated/build/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/build/dossiers/$id'
      preLoaderRoute: typeof AuthenticatedBuildDossiersIdRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/missions/': {
      id: '/_authenticated/build/missions/'
      path: '/'
      fullPath: '/build/missions/'
      preLoaderRoute: typeof AuthenticatedBuildMissionsIndexRouteImport
      parentRoute: typeof AuthenticatedBuildMissionsRoute
    }
    '/_authenticated/build/missions/$id': {
      id: '/_authenticated/build/missions/$id'
      path: '/$id'
      fullPath: '/build/missions/$id'
      preLoaderRoute: typeof AuthenticatedBuildMissionsIdRouteImport
      parentRoute: typeof AuthenticatedBuildMissionsRoute
    }
    '/_authenticated/build/missions/new': {
      id: '/_authenticated/build/missions/new'
      path: '/new'
      fullPath: '/build/missions/new'
      preLoaderRoute: typeof AuthenticatedBuildMissionsNewRouteImport
      parentRoute: typeof AuthenticatedBuildMissionsRoute
    }
    '/_authenticated/build/playbooks/': {
      id: '/_authenticated/build/playbooks/'
      path: '/playbooks'
      fullPath: '/build/playbooks/'
      preLoaderRoute: typeof AuthenticatedBuildPlaybooksIndexRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/playbooks/$id': {
      id: '/_authenticated/build/playbooks/$id'
      path: '/playbooks/$id'
      fullPath: '/build/playbooks/$id'
      preLoaderRoute: typeof AuthenticatedBuildPlaybooksIdRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/requests/': {
      id: '/_authenticated/build/requests/'
      path: '/requests'
      fullPath: '/build/requests/'
      preLoaderRoute: typeof AuthenticatedBuildRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/requests/$id': {
      id: '/_authenticated/build/requests/$id'
      path: '/requests/$id'
      fullPath: '/build/requests/$id'
      preLoaderRoute: typeof AuthenticatedBuildRequestsIdRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/build/workspaces/': {
      id: '/_authenticated/build/workspaces/'
      path: '/workspaces'
      fullPath: '/build/workspaces/'
      preLoaderRoute: typeof AuthenticatedBuildWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedBuildRouteRoute
    }
    '/_authenticated/marketplace/cases/': {
      id: '/_authenticated/marketplace/cases/'
      path: '/cases'
      fullPath: '/marketplace/cases/'
      preLoaderRoute: typeof AuthenticatedMarketplaceCasesIndexRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRouteRoute
    }
    '/_authenticated/marketplace/cases/$caseId': {
      id: '/_authenticated/marketplace/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/marketplace/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedMarketplaceCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRouteRoute
    }
    '/_authenticated/marketplace/pricing/': {
      id: '/_authenticated/marketplace/pricing/'
      path: '/pricing'
      fullPath: '/marketplace/pricing/'
      preLoaderRoute: typeof AuthenticatedMarketplacePricingIndexRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRouteRoute
    }
    '/_authenticated/marketplace/pricing/$binderId': {
      id: '/_authenticated/marketplace/pricing/$binderId'
      path: '/pricing/$binderId'
      fullPath: '/marketplace/pricing/$binderId'
      preLoaderRoute: typeof AuthenticatedMarketplacePricingBinderIdRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRouteRoute
    }
    '/_authenticated/portal/demos/new': {
      id: '/_authenticated/portal/demos/new'
      path: '/new'
      fullPath: '/portal/demos/new'
      preLoaderRoute: typeof AuthenticatedPortalDemosNewRouteImport
      parentRoute: typeof AuthenticatedPortalDemosRoute
    }
    '/_authenticated/portal/dossiers/$id': {
      id: '/_authenticated/portal/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/portal/dossiers/$id'
      preLoaderRoute: typeof AuthenticatedPortalDossiersIdRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/api/internal/analytics/metrics': {
      id: '/api/internal/analytics/metrics'
      path: '/api/internal/analytics/metrics'
      fullPath: '/api/internal/analytics/metrics'
      preLoaderRoute: typeof ApiInternalAnalyticsMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/hermes/prospect-funnels': {
      id: '/api/internal/hermes/prospect-funnels'
      path: '/api/internal/hermes/prospect-funnels'
      fullPath: '/api/internal/hermes/prospect-funnels'
      preLoaderRoute: typeof ApiInternalHermesProspectFunnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/hermes/prospect-funnels/metrics': {
      id: '/api/internal/hermes/prospect-funnels/metrics'
      path: '/metrics'
      fullPath: '/api/internal/hermes/prospect-funnels/metrics'
      preLoaderRoute: typeof ApiInternalHermesProspectFunnelsMetricsRouteImport
      parentRoute: typeof ApiInternalHermesProspectFunnelsRoute
    }
  }
}

interface AuthenticatedAtelierRouteRouteChildren {
  AuthenticatedAtelierIndexRoute: typeof AuthenticatedAtelierIndexRoute
  AuthenticatedAtelierCasesCaseIdRoute: typeof AuthenticatedAtelierCasesCaseIdRoute
}

const AuthenticatedAtelierRouteRouteChildren: AuthenticatedAtelierRouteRouteChildren =
  {
    AuthenticatedAtelierIndexRoute: AuthenticatedAtelierIndexRoute,
    AuthenticatedAtelierCasesCaseIdRoute: AuthenticatedAtelierCasesCaseIdRoute,
  }

const AuthenticatedAtelierRouteRouteWithChildren =
  AuthenticatedAtelierRouteRoute._addFileChildren(
    AuthenticatedAtelierRouteRouteChildren,
  )

interface AuthenticatedBuildMissionsRouteChildren {
  AuthenticatedBuildMissionsIdRoute: typeof AuthenticatedBuildMissionsIdRoute
  AuthenticatedBuildMissionsNewRoute: typeof AuthenticatedBuildMissionsNewRoute
  AuthenticatedBuildMissionsIndexRoute: typeof AuthenticatedBuildMissionsIndexRoute
}

const AuthenticatedBuildMissionsRouteChildren: AuthenticatedBuildMissionsRouteChildren =
  {
    AuthenticatedBuildMissionsIdRoute: AuthenticatedBuildMissionsIdRoute,
    AuthenticatedBuildMissionsNewRoute: AuthenticatedBuildMissionsNewRoute,
    AuthenticatedBuildMissionsIndexRoute: AuthenticatedBuildMissionsIndexRoute,
  }

const AuthenticatedBuildMissionsRouteWithChildren =
  AuthenticatedBuildMissionsRoute._addFileChildren(
    AuthenticatedBuildMissionsRouteChildren,
  )

interface AuthenticatedBuildRouteRouteChildren {
  AuthenticatedBuildActivityRoute: typeof AuthenticatedBuildActivityRoute
  AuthenticatedBuildDashboardRoute: typeof AuthenticatedBuildDashboardRoute
  AuthenticatedBuildKnowledgeRoute: typeof AuthenticatedBuildKnowledgeRoute
  AuthenticatedBuildMissionsRoute: typeof AuthenticatedBuildMissionsRouteWithChildren
  AuthenticatedBuildOnboardingRoute: typeof AuthenticatedBuildOnboardingRoute
  AuthenticatedBuildSettingsRoute: typeof AuthenticatedBuildSettingsRoute
  AuthenticatedBuildIndexRoute: typeof AuthenticatedBuildIndexRoute
  AuthenticatedBuildDossiersIdRoute: typeof AuthenticatedBuildDossiersIdRoute
  AuthenticatedBuildPlaybooksIdRoute: typeof AuthenticatedBuildPlaybooksIdRoute
  AuthenticatedBuildRequestsIdRoute: typeof AuthenticatedBuildRequestsIdRoute
  AuthenticatedBuildDossiersIndexRoute: typeof AuthenticatedBuildDossiersIndexRoute
  AuthenticatedBuildPlaybooksIndexRoute: typeof AuthenticatedBuildPlaybooksIndexRoute
  AuthenticatedBuildRequestsIndexRoute: typeof AuthenticatedBuildRequestsIndexRoute
  AuthenticatedBuildWorkspacesIndexRoute: typeof AuthenticatedBuildWorkspacesIndexRoute
}

const AuthenticatedBuildRouteRouteChildren: AuthenticatedBuildRouteRouteChildren =
  {
    AuthenticatedBuildActivityRoute: AuthenticatedBuildActivityRoute,
    AuthenticatedBuildDashboardRoute: AuthenticatedBuildDashboardRoute,
    AuthenticatedBuildKnowledgeRoute: AuthenticatedBuildKnowledgeRoute,
    AuthenticatedBuildMissionsRoute:
      AuthenticatedBuildMissionsRouteWithChildren,
    AuthenticatedBuildOnboardingRoute: AuthenticatedBuildOnboardingRoute,
    AuthenticatedBuildSettingsRoute: AuthenticatedBuildSettingsRoute,
    AuthenticatedBuildIndexRoute: AuthenticatedBuildIndexRoute,
    AuthenticatedBuildDossiersIdRoute: AuthenticatedBuildDossiersIdRoute,
    AuthenticatedBuildPlaybooksIdRoute: AuthenticatedBuildPlaybooksIdRoute,
    AuthenticatedBuildRequestsIdRoute: AuthenticatedBuildRequestsIdRoute,
    AuthenticatedBuildDossiersIndexRoute: AuthenticatedBuildDossiersIndexRoute,
    AuthenticatedBuildPlaybooksIndexRoute:
      AuthenticatedBuildPlaybooksIndexRoute,
    AuthenticatedBuildRequestsIndexRoute: AuthenticatedBuildRequestsIndexRoute,
    AuthenticatedBuildWorkspacesIndexRoute:
      AuthenticatedBuildWorkspacesIndexRoute,
  }

const AuthenticatedBuildRouteRouteWithChildren =
  AuthenticatedBuildRouteRoute._addFileChildren(
    AuthenticatedBuildRouteRouteChildren,
  )

interface AuthenticatedMarketplaceRouteRouteChildren {
  AuthenticatedMarketplaceBindersRoute: typeof AuthenticatedMarketplaceBindersRoute
  AuthenticatedMarketplaceIndexRoute: typeof AuthenticatedMarketplaceIndexRoute
  AuthenticatedMarketplaceCasesCaseIdRoute: typeof AuthenticatedMarketplaceCasesCaseIdRoute
  AuthenticatedMarketplacePricingBinderIdRoute: typeof AuthenticatedMarketplacePricingBinderIdRoute
  AuthenticatedMarketplaceCasesIndexRoute: typeof AuthenticatedMarketplaceCasesIndexRoute
  AuthenticatedMarketplacePricingIndexRoute: typeof AuthenticatedMarketplacePricingIndexRoute
}

const AuthenticatedMarketplaceRouteRouteChildren: AuthenticatedMarketplaceRouteRouteChildren =
  {
    AuthenticatedMarketplaceBindersRoute: AuthenticatedMarketplaceBindersRoute,
    AuthenticatedMarketplaceIndexRoute: AuthenticatedMarketplaceIndexRoute,
    AuthenticatedMarketplaceCasesCaseIdRoute:
      AuthenticatedMarketplaceCasesCaseIdRoute,
    AuthenticatedMarketplacePricingBinderIdRoute:
      AuthenticatedMarketplacePricingBinderIdRoute,
    AuthenticatedMarketplaceCasesIndexRoute:
      AuthenticatedMarketplaceCasesIndexRoute,
    AuthenticatedMarketplacePricingIndexRoute:
      AuthenticatedMarketplacePricingIndexRoute,
  }

const AuthenticatedMarketplaceRouteRouteWithChildren =
  AuthenticatedMarketplaceRouteRoute._addFileChildren(
    AuthenticatedMarketplaceRouteRouteChildren,
  )

interface AuthenticatedMesLivresRouteRouteChildren {
  AuthenticatedMesLivresCaseIdRoute: typeof AuthenticatedMesLivresCaseIdRoute
  AuthenticatedMesLivresIndexRoute: typeof AuthenticatedMesLivresIndexRoute
}

const AuthenticatedMesLivresRouteRouteChildren: AuthenticatedMesLivresRouteRouteChildren =
  {
    AuthenticatedMesLivresCaseIdRoute: AuthenticatedMesLivresCaseIdRoute,
    AuthenticatedMesLivresIndexRoute: AuthenticatedMesLivresIndexRoute,
  }

const AuthenticatedMesLivresRouteRouteWithChildren =
  AuthenticatedMesLivresRouteRoute._addFileChildren(
    AuthenticatedMesLivresRouteRouteChildren,
  )

interface AuthenticatedPortalDemosRouteChildren {
  AuthenticatedPortalDemosNewRoute: typeof AuthenticatedPortalDemosNewRoute
}

const AuthenticatedPortalDemosRouteChildren: AuthenticatedPortalDemosRouteChildren =
  {
    AuthenticatedPortalDemosNewRoute: AuthenticatedPortalDemosNewRoute,
  }

const AuthenticatedPortalDemosRouteWithChildren =
  AuthenticatedPortalDemosRoute._addFileChildren(
    AuthenticatedPortalDemosRouteChildren,
  )

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalBillingRoute: typeof AuthenticatedPortalBillingRoute
  AuthenticatedPortalDemosRoute: typeof AuthenticatedPortalDemosRouteWithChildren
  AuthenticatedPortalMissionsRoute: typeof AuthenticatedPortalMissionsRoute
  AuthenticatedPortalSettingsRoute: typeof AuthenticatedPortalSettingsRoute
  AuthenticatedPortalSetupRoute: typeof AuthenticatedPortalSetupRoute
  AuthenticatedPortalTeamRoute: typeof AuthenticatedPortalTeamRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalDossiersIdRoute: typeof AuthenticatedPortalDossiersIdRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalBillingRoute: AuthenticatedPortalBillingRoute,
    AuthenticatedPortalDemosRoute: AuthenticatedPortalDemosRouteWithChildren,
    AuthenticatedPortalMissionsRoute: AuthenticatedPortalMissionsRoute,
    AuthenticatedPortalSettingsRoute: AuthenticatedPortalSettingsRoute,
    AuthenticatedPortalSetupRoute: AuthenticatedPortalSetupRoute,
    AuthenticatedPortalTeamRoute: AuthenticatedPortalTeamRoute,
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
    AuthenticatedPortalDossiersIdRoute: AuthenticatedPortalDossiersIdRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtelierRouteRoute: typeof AuthenticatedAtelierRouteRouteWithChildren
  AuthenticatedBuildRouteRoute: typeof AuthenticatedBuildRouteRouteWithChildren
  AuthenticatedMarketplaceRouteRoute: typeof AuthenticatedMarketplaceRouteRouteWithChildren
  AuthenticatedMesLivresRouteRoute: typeof AuthenticatedMesLivresRouteRouteWithChildren
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtelierRouteRoute: AuthenticatedAtelierRouteRouteWithChildren,
  AuthenticatedBuildRouteRoute: AuthenticatedBuildRouteRouteWithChildren,
  AuthenticatedMarketplaceRouteRoute:
    AuthenticatedMarketplaceRouteRouteWithChildren,
  AuthenticatedMesLivresRouteRoute:
    AuthenticatedMesLivresRouteRouteWithChildren,
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiInternalHermesProspectFunnelsRouteChildren {
  ApiInternalHermesProspectFunnelsMetricsRoute: typeof ApiInternalHermesProspectFunnelsMetricsRoute
}

const ApiInternalHermesProspectFunnelsRouteChildren: ApiInternalHermesProspectFunnelsRouteChildren =
  {
    ApiInternalHermesProspectFunnelsMetricsRoute:
      ApiInternalHermesProspectFunnelsMetricsRoute,
  }

const ApiInternalHermesProspectFunnelsRouteWithChildren =
  ApiInternalHermesProspectFunnelsRoute._addFileChildren(
    ApiInternalHermesProspectFunnelsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CandidatureAtelierRoute: CandidatureAtelierRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  DeckBuildersRoute: DeckBuildersRoute,
  ExampleProjectBriefRoute: ExampleProjectBriefRoute,
  FineBinderyRoute: FineBinderyRoute,
  FreeInquiryAuditRoute: FreeInquiryAuditRoute,
  HowItWorksRoute: HowItWorksRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PartenairesRelieursRoute: PartenairesRelieursRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PrivateBetaRoute: PrivateBetaRoute,
  ReliureRoute: ReliureRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
  TermsRoute: TermsRoute,
  ASlugRoute: ASlugRoute,
  DemoDeckProjectRoute: DemoDeckProjectRoute,
  InvitationAtelierTokenRoute: InvitationAtelierTokenRoute,
  MPublicTokenRoute: MPublicTokenRoute,
  ProjectSummaryAccessTokenRoute: ProjectSummaryAccessTokenRoute,
  ApiPublicAnalyzeSiteRoute: ApiPublicAnalyzeSiteRoute,
  ApiPublicBuildPublicIntakeRoute: ApiPublicBuildPublicIntakeRoute,
  ApiPublicBuildRuntimeRoute: ApiPublicBuildRuntimeRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicFaqAskRoute: ApiPublicFaqAskRoute,
  ApiPublicProjectSummaryRoute: ApiPublicProjectSummaryRoute,
  ApiPublicTrackViewRoute: ApiPublicTrackViewRoute,
  ApiInternalAnalyticsMetricsRoute: ApiInternalAnalyticsMetricsRoute,
  ApiInternalHermesProspectFunnelsRoute:
    ApiInternalHermesProspectFunnelsRouteWithChildren,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
