/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivateBetaRouteImport } from './routes/private-beta'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FreeInquiryAuditRouteImport } from './routes/free-inquiry-audit'
import { Route as ExampleProjectBriefRouteImport } from './routes/example-project-brief'
import { Route as DeckBuildersRouteImport } from './routes/deck-builders'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MPublicTokenRouteImport } from './routes/m.$publicToken'
import { Route as DemoDeckProjectRouteImport } from './routes/demo.deck-project'
import { Route as ApiPublicBuildRuntimeRouteImport } from './routes/api/public/build-runtime'
import { Route as ApiPublicBuildPublicIntakeRouteImport } from './routes/api/public/build-public-intake'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateBetaRoute = PrivateBetaRouteImport.update({
  id: '/private-beta',
  path: '/private-beta',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeInquiryAuditRoute = FreeInquiryAuditRouteImport.update({
  id: '/free-inquiry-audit',
  path: '/free-inquiry-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleProjectBriefRoute = ExampleProjectBriefRouteImport.update({
  id: '/example-project-brief',
  path: '/example-project-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckBuildersRoute = DeckBuildersRouteImport.update({
  id: '/deck-builders',
  path: '/deck-builders',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MPublicTokenRoute = MPublicTokenRouteImport.update({
  id: '/m/$publicToken',
  path: '/m/$publicToken',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDeckProjectRoute = DemoDeckProjectRouteImport.update({
  id: '/demo/deck-project',
  path: '/demo/deck-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildRuntimeRoute = ApiPublicBuildRuntimeRouteImport.update({
  id: '/api/public/build-runtime',
  path: '/api/public/build-runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildPublicIntakeRoute =
  ApiPublicBuildPublicIntakeRouteImport.update({
    id: '/api/public/build-public-intake',
    path: '/api/public/build-public-intake',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck-builders': typeof DeckBuildersRoute
  '/example-project-brief': typeof ExampleProjectBriefRoute
  '/free-inquiry-audit': typeof FreeInquiryAuditRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/private-beta': typeof PrivateBetaRoute
  '/terms': typeof TermsRoute
  '/demo/deck-project': typeof DemoDeckProjectRoute
  '/m/$publicToken': typeof MPublicTokenRoute
  '/api/public/build-public-intake': typeof ApiPublicBuildPublicIntakeRoute
  '/api/public/build-runtime': typeof ApiPublicBuildRuntimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck-builders': typeof DeckBuildersRoute
  '/example-project-brief': typeof ExampleProjectBriefRoute
  '/free-inquiry-audit': typeof FreeInquiryAuditRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/private-beta': typeof PrivateBetaRoute
  '/terms': typeof TermsRoute
  '/demo/deck-project': typeof DemoDeckProjectRoute
  '/m/$publicToken': typeof MPublicTokenRoute
  '/api/public/build-public-intake': typeof ApiPublicBuildPublicIntakeRoute
  '/api/public/build-runtime': typeof ApiPublicBuildRuntimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck-builders': typeof DeckBuildersRoute
  '/example-project-brief': typeof ExampleProjectBriefRoute
  '/free-inquiry-audit': typeof FreeInquiryAuditRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/private-beta': typeof PrivateBetaRoute
  '/terms': typeof TermsRoute
  '/demo/deck-project': typeof DemoDeckProjectRoute
  '/m/$publicToken': typeof MPublicTokenRoute
  '/api/public/build-public-intake': typeof ApiPublicBuildPublicIntakeRoute
  '/api/public/build-runtime': typeof ApiPublicBuildRuntimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deck-builders'
    | '/example-project-brief'
    | '/free-inquiry-audit'
    | '/how-it-works'
    | '/privacy'
    | '/private-beta'
    | '/terms'
    | '/demo/deck-project'
    | '/m/$publicToken'
    | '/api/public/build-public-intake'
    | '/api/public/build-runtime'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deck-builders'
    | '/example-project-brief'
    | '/free-inquiry-audit'
    | '/how-it-works'
    | '/privacy'
    | '/private-beta'
    | '/terms'
    | '/demo/deck-project'
    | '/m/$publicToken'
    | '/api/public/build-public-intake'
    | '/api/public/build-runtime'
  id:
    | '__root__'
    | '/'
    | '/deck-builders'
    | '/example-project-brief'
    | '/free-inquiry-audit'
    | '/how-it-works'
    | '/privacy'
    | '/private-beta'
    | '/terms'
    | '/demo/deck-project'
    | '/m/$publicToken'
    | '/api/public/build-public-intake'
    | '/api/public/build-runtime'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckBuildersRoute: typeof DeckBuildersRoute
  ExampleProjectBriefRoute: typeof ExampleProjectBriefRoute
  FreeInquiryAuditRoute: typeof FreeInquiryAuditRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivateBetaRoute: typeof PrivateBetaRoute
  TermsRoute: typeof TermsRoute
  DemoDeckProjectRoute: typeof DemoDeckProjectRoute
  MPublicTokenRoute: typeof MPublicTokenRoute
  ApiPublicBuildPublicIntakeRoute: typeof ApiPublicBuildPublicIntakeRoute
  ApiPublicBuildRuntimeRoute: typeof ApiPublicBuildRuntimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-beta': {
      id: '/private-beta'
      path: '/private-beta'
      fullPath: '/private-beta'
      preLoaderRoute: typeof PrivateBetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-inquiry-audit': {
      id: '/free-inquiry-audit'
      path: '/free-inquiry-audit'
      fullPath: '/free-inquiry-audit'
      preLoaderRoute: typeof FreeInquiryAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example-project-brief': {
      id: '/example-project-brief'
      path: '/example-project-brief'
      fullPath: '/example-project-brief'
      preLoaderRoute: typeof ExampleProjectBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck-builders': {
      id: '/deck-builders'
      path: '/deck-builders'
      fullPath: '/deck-builders'
      preLoaderRoute: typeof DeckBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$publicToken': {
      id: '/m/$publicToken'
      path: '/m/$publicToken'
      fullPath: '/m/$publicToken'
      preLoaderRoute: typeof MPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/deck-project': {
      id: '/demo/deck-project'
      path: '/demo/deck-project'
      fullPath: '/demo/deck-project'
      preLoaderRoute: typeof DemoDeckProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/build-runtime': {
      id: '/api/public/build-runtime'
      path: '/api/public/build-runtime'
      fullPath: '/api/public/build-runtime'
      preLoaderRoute: typeof ApiPublicBuildRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/build-public-intake': {
      id: '/api/public/build-public-intake'
      path: '/api/public/build-public-intake'
      fullPath: '/api/public/build-public-intake'
      preLoaderRoute: typeof ApiPublicBuildPublicIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckBuildersRoute: DeckBuildersRoute,
  ExampleProjectBriefRoute: ExampleProjectBriefRoute,
  FreeInquiryAuditRoute: FreeInquiryAuditRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  PrivateBetaRoute: PrivateBetaRoute,
  TermsRoute: TermsRoute,
  DemoDeckProjectRoute: DemoDeckProjectRoute,
  MPublicTokenRoute: MPublicTokenRoute,
  ApiPublicBuildPublicIntakeRoute: ApiPublicBuildPublicIntakeRoute,
  ApiPublicBuildRuntimeRoute: ApiPublicBuildRuntimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
