-- 1. Draft Playbooks generated by a client belong to that workspace only.
ALTER TABLE public.build_playbooks
  ADD COLUMN IF NOT EXISTS workspace_id uuid REFERENCES public.build_workspaces(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS build_playbooks_workspace_id_idx
  ON public.build_playbooks (workspace_id) WHERE workspace_id IS NOT NULL;

-- 2. One self-service onboarding record per workspace.
CREATE TABLE public.build_workspace_onboarding (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL UNIQUE REFERENCES public.build_workspaces(id) ON DELETE CASCADE,
  created_by uuid NOT NULL,
  status text NOT NULL DEFAULT 'started',
  site_url text,
  final_url text,
  analysis jsonb,
  analyzed_at timestamptz,
  confirmed_business_type text,
  confirmed_product text,
  playbook_id uuid REFERENCES public.build_playbooks(id) ON DELETE SET NULL,
  draft_version integer NOT NULL DEFAULT 0,
  branding jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_analyze_request_id text,
  last_generate_request_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT ALL ON public.build_workspace_onboarding TO service_role;
ALTER TABLE public.build_workspace_onboarding ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access to build_workspace_onboarding"
  ON public.build_workspace_onboarding FOR ALL TO anon, authenticated
  USING (false) WITH CHECK (false);

CREATE TRIGGER build_workspace_onboarding_touch_updated_at
  BEFORE UPDATE ON public.build_workspace_onboarding
  FOR EACH ROW EXECUTE FUNCTION public.build_touch_updated_at();

-- 3. AI run log: rate limiting + cost/latency/error observability.
CREATE TABLE public.build_workspace_ai_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES public.build_workspaces(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  action text NOT NULL,
  request_id text,
  status text NOT NULL,
  latency_ms integer,
  error text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX build_workspace_ai_runs_rate_idx
  ON public.build_workspace_ai_runs (workspace_id, action, created_at DESC);

GRANT ALL ON public.build_workspace_ai_runs TO service_role;
ALTER TABLE public.build_workspace_ai_runs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access to build_workspace_ai_runs"
  ON public.build_workspace_ai_runs FOR ALL TO anon, authenticated
  USING (false) WITH CHECK (false);